---
title: "Untitled"
author: ""
date: "`r format(Sys.Date())`"
output: html_document
--- 
```{r, echo = FALSE}
merged_haploped_pheno_gt=read.csv("~/Documents/PPARGC1A/Analysis/pheno_gt_ato_g.csv", header=TRUE, sep="\t")
merged_haploped_pheno_gt$DOM_c =ifelse( merged_haploped_pheno_gt$RS8192678_CC1_CT2_TT3 ==1 | merged_haploped_pheno_gt$RS8192678_CC1_CT2_TT3 ==2 , 1, 0)
merged_haploped_pheno_gt$DOM_t =ifelse( merged_haploped_pheno_gt$RS8192678_CC1_CT2_TT3 ==3 | merged_haploped_pheno_gt$RS8192678_CC1_CT2_TT3 ==2 , 1, 0)
merged_haploped_pheno_gt$het_adv =ifelse( merged_haploped_pheno_gt$RS8192678_CC1_CT2_TT3 ==2 , 1, 0)



merged_haploped_pheno_gt$SEX.x <- as.factor(merged_haploped_pheno_gt$SEX.x)
merged_haploped_pheno_gt$DIABETES <- as.factor(merged_haploped_pheno_gt$DIABETES)

cases=subset(merged_haploped_pheno_gt, merged_haploped_pheno_gt$GOUTAFFSTAT==2)
controls=subset(merged_haploped_pheno_gt, merged_haploped_pheno_gt$GOUTAFFSTAT==1)
nzm=subset(merged_haploped_pheno_gt, merged_haploped_pheno_gt$ETHNICITY=="1.0 NZ Maori")
nzm_c=subset(nzm, nzm$FULLEPGTAFF==1)
nzm_g=subset(nzm, nzm$FULLEPGTAFF==2)

samoan=subset(merged_haploped_pheno_gt, merged_haploped_pheno_gt$ETHNICITY=="1.0 Samoan")
samoan_g=subset(samoan, samoan$FULLWPGTAFF==2)
samoan_c=subset(samoan, samoan$FULLWPGTAFF==1)

tongan=subset(merged_haploped_pheno_gt, merged_haploped_pheno_gt$ETHNICITY=="1.0 Tongan")
tongan_c=subset(tongan,tongan$FULLWPGTAFF==1)
tongan_g=subset(tongan, tongan$FULLWPGTAFF==2)

cim=subset(merged_haploped_pheno_gt, merged_haploped_pheno_gt$ETHNICITY=="1.0 CI Maori")
cim_c=subset(cim, cim$FULLEPGTAFF==1)
cim_g=subset(cim, cim$FULLEPGTAFF==2)

merged_haploped_pheno_gt$ETHNICITY[merged_haploped_pheno_gt$ETHNICITY == "1.0 Caucasain"] = "1.0 Caucasian"

##CAU groups
CAU=subset(merged_haploped_pheno_gt, merged_haploped_pheno_gt$FULLCAUGTAFF==1 | merged_haploped_pheno_gt$FULLCAUGTAFF==2)
CAU_g=subset(CAU, CAU$FULLCAUGTAFF==2)
CAU_c=subset(CAU, CAU$FULLCAUGTAFF==1)




CAU_mod=CAU
CAU_mod$STANCESTRY=rep(0, length(CAU_mod[,1]))
CAU_mod=CAU_mod[c("FULLCAUGTAFF", "DIABETES", "STANCESTRY", "SEX.x","AGECOL", "BMI", "RS8192678_CC1_CT2_TT3", "DOM_c","DOM_t", "het_adv")]
colnames(CAU_mod) = c("FULLGTAFF", "DIABETES", "STANCESTRY", "SEX.x","AGECOL", "BMI", "RS8192678_CC1_CT2_TT3", "DOM_c","DOM_t", "het_adv")
CAU_mod$POP=rep("CAU", length(CAU_mod[,1]))

```


# additive
```{r}
cau_glm_additive=glm(as.factor(CAU$DIABETES) ~ as.factor(CAU$FULLCAUGTAFF)+CAU$BMI + CAU$AGECOL + as.factor(CAU$SEX.x) +  CAU$RS8192678_CC1_CT2_TT3, family="binomial")
nzm_glm_additive=glm( as.factor(nzm$DIABETES) ~ as.factor(nzm$FULLEPGTAFF) +nzm$BMI+ nzm$AGECOL + as.factor(nzm$SEX.x) + nzm$STANCESTRY+ nzm$RS8192678_CC1_CT2_TT3, family="binomial")
cim_glm_additive=glm(as.factor(cim$DIABETES)  ~ as.factor(cim$FULLEPGTAFF)+cim$BMI + cim$AGECOL + as.factor(cim$SEX.x) + cim$STANCESTRY+ cim$RS8192678_CC1_CT2_TT3, family="binomial")
samoan_glm_additive=glm(as.factor(samoan$DIABETES) ~ as.factor(samoan$FULLWPGTAFF) +samoan$BMI+ samoan$AGECOL + as.factor(samoan$SEX.x) + samoan$STANCESTRY+ samoan$RS8192678_CC1_CT2_TT3, family="binomial")
tongan_glm_additive=glm(as.factor(tongan$DIABETES)  ~ as.factor(tongan$FULLWPGTAFF)+ tongan$BMI+ tongan$AGECOL + as.factor(tongan$SEX.x) + tongan$STANCESTRY+ tongan$RS8192678_CC1_CT2_TT3, family="binomial")


round(cbind(exp(cbind(OR= coef(cau_glm_additive), confint(cau_glm_additive))),Pvalue= summary(cau_glm_additive)$coefficients[,4]),3)
round(cbind(exp(cbind(OR=coef(nzm_glm_additive), confint(nzm_glm_additive))), Pvalue=summary(nzm_glm_additive)$coefficients[,4]), 3)
round(cbind(exp(cbind(OR=coef(cim_glm_additive), confint(cim_glm_additive))), Pvalue=summary(cim_glm_additive)$coefficients[,4]), 3)
round(cbind(exp(cbind(OR=coef(samoan_glm_additive), confint(samoan_glm_additive))), Pvalue=summary(samoan_glm_additive)$coefficients[,4]),3)
round(cbind(exp(cbind(OR=coef(tongan_glm_additive), confint(tongan_glm_additive))), Pvalue=summary(tongan_glm_additive)$coefficients[,4]),3)

```

## add male
```{r add male}
cau_glm_additive=glm(as.factor(DIABETES) ~ as.factor(FULLCAUGTAFF)+BMI + AGECOL + RS8192678_CC1_CT2_TT3, family="binomial", data = CAU[CAU$SEX.x ==1, ])
nzm_glm_additive=glm( as.factor(DIABETES) ~ as.factor(FULLEPGTAFF) +BMI+ AGECOL + STANCESTRY+ RS8192678_CC1_CT2_TT3, family="binomial", data = nzm[nzm$SEX.x ==1, ])
cim_glm_additive=glm(as.factor(DIABETES)  ~ as.factor(FULLEPGTAFF)+BMI + AGECOL + STANCESTRY+ RS8192678_CC1_CT2_TT3, family="binomial", data = cim[cim$SEX.x == 1,])
samoan_glm_additive=glm(as.factor(DIABETES) ~ as.factor(FULLWPGTAFF) +BMI+ AGECOL + STANCESTRY+ RS8192678_CC1_CT2_TT3, family="binomial", data = samoan[samoan$SEX.x ==1,])
tongan_glm_additive=glm(as.factor(DIABETES)  ~ as.factor(FULLWPGTAFF)+ BMI+ AGECOL + STANCESTRY+ RS8192678_CC1_CT2_TT3, family="binomial", data = tongan[tongan$SEX.x ==1,])


round(cbind(exp(cbind(OR= coef(cau_glm_additive), confint(cau_glm_additive))),Pvalue= summary(cau_glm_additive)$coefficients[,4]),3)
round(cbind(exp(cbind(OR=coef(nzm_glm_additive), confint(nzm_glm_additive))), Pvalue=summary(nzm_glm_additive)$coefficients[,4]), 3)
round(cbind(exp(cbind(OR=coef(cim_glm_additive), confint(cim_glm_additive))), Pvalue=summary(cim_glm_additive)$coefficients[,4]), 3)
round(cbind(exp(cbind(OR=coef(samoan_glm_additive), confint(samoan_glm_additive))), Pvalue=summary(samoan_glm_additive)$coefficients[,4]),3)
round(cbind(exp(cbind(OR=coef(tongan_glm_additive), confint(tongan_glm_additive))), Pvalue=summary(tongan_glm_additive)$coefficients[,4]),3)
```

## add female
```{r add female}
cau_glm_additive=glm(as.factor(DIABETES) ~ as.factor(FULLCAUGTAFF)+BMI + AGECOL + RS8192678_CC1_CT2_TT3, family="binomial", data = CAU[CAU$SEX.x ==2, ])
nzm_glm_additive=glm( as.factor(DIABETES) ~ as.factor(FULLEPGTAFF) +BMI+ AGECOL + STANCESTRY+ RS8192678_CC1_CT2_TT3, family="binomial", data = nzm[nzm$SEX.x ==2, ])
cim_glm_additive=glm(as.factor(DIABETES)  ~ as.factor(FULLEPGTAFF)+BMI + AGECOL + STANCESTRY+ RS8192678_CC1_CT2_TT3, family="binomial", data = cim[cim$SEX.x == 2,])
samoan_glm_additive=glm(as.factor(DIABETES) ~ as.factor(FULLWPGTAFF) +BMI+ AGECOL + STANCESTRY+ RS8192678_CC1_CT2_TT3, family="binomial", data = samoan[samoan$SEX.x ==2,])
tongan_glm_additive=glm(as.factor(DIABETES)  ~ as.factor(FULLWPGTAFF)+ BMI+ AGECOL + STANCESTRY+ RS8192678_CC1_CT2_TT3, family="binomial", data = tongan[tongan$SEX.x ==2,])


round(cbind(exp(cbind(OR= coef(cau_glm_additive), confint(cau_glm_additive))),Pvalue= summary(cau_glm_additive)$coefficients[,4]),3)
round(cbind(exp(cbind(OR=coef(nzm_glm_additive), confint(nzm_glm_additive))), Pvalue=summary(nzm_glm_additive)$coefficients[,4]), 3)
round(cbind(exp(cbind(OR=coef(cim_glm_additive), confint(cim_glm_additive))), Pvalue=summary(cim_glm_additive)$coefficients[,4]), 3)
round(cbind(exp(cbind(OR=coef(samoan_glm_additive), confint(samoan_glm_additive))), Pvalue=summary(samoan_glm_additive)$coefficients[,4]),3)
round(cbind(exp(cbind(OR=coef(tongan_glm_additive), confint(tongan_glm_additive))), Pvalue=summary(tongan_glm_additive)$coefficients[,4]),3)
```

# dom c
```{r domc}
cau_glm_domc=glm(as.factor(CAU$DIABETES) ~ as.factor(CAU$FULLCAUGTAFF)+CAU$BMI + CAU$AGECOL + as.factor(CAU$SEX.x) +  CAU$DOM_c, family="binomial")
nzm_glm_domc=glm( as.factor(nzm$DIABETES) ~ as.factor(nzm$FULLEPGTAFF) +nzm$BMI+ nzm$AGECOL + as.factor(nzm$SEX.x) + nzm$STANCESTRY+ nzm$DOM_c, family="binomial")
cim_glm_domc=glm(as.factor(cim$DIABETES)  ~ as.factor(cim$FULLEPGTAFF)+cim$BMI + cim$AGECOL + as.factor(cim$SEX.x) + cim$STANCESTRY+ cim$DOM_c, family="binomial")
samoan_glm_domc=glm(as.factor(samoan$DIABETES) ~ as.factor(samoan$FULLWPGTAFF) +samoan$BMI+ samoan$AGECOL + as.factor(samoan$SEX.x) + samoan$STANCESTRY+ samoan$DOM_c, family="binomial")
tongan_glm_domc=glm(as.factor(tongan$DIABETES)  ~ as.factor(tongan$FULLWPGTAFF)+ tongan$BMI+ tongan$AGECOL + as.factor(tongan$SEX.x) + tongan$STANCESTRY+ tongan$DOM_c, family="binomial")

round(cbind(exp(cbind(OR= coef(cau_glm_domc), confint(cau_glm_domc))),Pvalue= summary(cau_glm_domc)$coefficients[,4]),3)
round(cbind(exp(cbind(OR=coef(nzm_glm_domc), confint(nzm_glm_domc))), Pvalue=summary(nzm_glm_domc)$coefficients[,4]), 3)
round(cbind(exp(cbind(OR=coef(cim_glm_domc), confint(cim_glm_domc))), Pvalue=summary(cim_glm_domc)$coefficients[,4]), 3)
round(cbind(exp(cbind(OR=coef(samoan_glm_domc), confint(samoan_glm_domc))), Pvalue=summary(samoan_glm_domc)$coefficients[,4]),3)
round(cbind(exp(cbind(OR=coef(tongan_glm_domc), confint(tongan_glm_domc))), Pvalue=summary(tongan_glm_domc)$coefficients[,4]),3)
```

## domc male
```{r domc male}
cau_glm_domc=glm(as.factor(DIABETES) ~ as.factor(FULLCAUGTAFF)+BMI + AGECOL +   DOM_c, family="binomial", data=CAU[CAU$SEX.x ==1, ])
nzm_glm_domc=glm( as.factor(DIABETES) ~ as.factor(FULLEPGTAFF) +BMI+ AGECOL + STANCESTRY+ DOM_c, family="binomial", data = nzm[nzm$SEX.x ==1,])
cim_glm_domc=glm(as.factor(DIABETES)  ~ as.factor(FULLEPGTAFF)+BMI + AGECOL + STANCESTRY+ DOM_c, family="binomial", data = cim[cim$SEX.x ==1,])
samoan_glm_domc=glm(as.factor(DIABETES) ~ as.factor(FULLWPGTAFF) +BMI+ AGECOL + STANCESTRY+ DOM_c, family="binomial", data = samoan[samoan$SEX.x ==1,])
tongan_glm_domc=glm(as.factor(DIABETES)  ~ as.factor(FULLWPGTAFF)+ BMI+ AGECOL + STANCESTRY+ DOM_c, family="binomial", data = tongan[tongan$SEX.x ==1,])

round(cbind(exp(cbind(OR= coef(cau_glm_domc), confint(cau_glm_domc))),Pvalue= summary(cau_glm_domc)$coefficients[,4]),3)
round(cbind(exp(cbind(OR=coef(nzm_glm_domc), confint(nzm_glm_domc))), Pvalue=summary(nzm_glm_domc)$coefficients[,4]), 3)
round(cbind(exp(cbind(OR=coef(cim_glm_domc), confint(cim_glm_domc))), Pvalue=summary(cim_glm_domc)$coefficients[,4]), 3)
round(cbind(exp(cbind(OR=coef(samoan_glm_domc), confint(samoan_glm_domc))), Pvalue=summary(samoan_glm_domc)$coefficients[,4]),3)
round(cbind(exp(cbind(OR=coef(tongan_glm_domc), confint(tongan_glm_domc))), Pvalue=summary(tongan_glm_domc)$coefficients[,4]),3)
```

## domc female
```{r domc female}
cau_glm_domc=glm(as.factor(DIABETES) ~ as.factor(FULLCAUGTAFF)+BMI + AGECOL +   DOM_c, family="binomial", data=CAU[CAU$SEX.x ==2, ])
nzm_glm_domc=glm( as.factor(DIABETES) ~ as.factor(FULLEPGTAFF) +BMI+ AGECOL + STANCESTRY+ DOM_c, family="binomial", data = nzm[nzm$SEX.x ==2,])
cim_glm_domc=glm(as.factor(DIABETES)  ~ as.factor(FULLEPGTAFF)+BMI + AGECOL + STANCESTRY+ DOM_c, family="binomial", data = cim[cim$SEX.x ==2,])
samoan_glm_domc=glm(as.factor(DIABETES) ~ as.factor(FULLWPGTAFF) +BMI+ AGECOL + STANCESTRY+ DOM_c, family="binomial", data = samoan[samoan$SEX.x ==2,])
tongan_glm_domc=glm(as.factor(DIABETES)  ~ as.factor(FULLWPGTAFF)+ BMI+ AGECOL + STANCESTRY+ DOM_c, family="binomial", data = tongan[tongan$SEX.x ==2,])

round(cbind(exp(cbind(OR= coef(cau_glm_domc), confint(cau_glm_domc))),Pvalue= summary(cau_glm_domc)$coefficients[,4]),3)
round(cbind(exp(cbind(OR=coef(nzm_glm_domc), confint(nzm_glm_domc))), Pvalue=summary(nzm_glm_domc)$coefficients[,4]), 3)
round(cbind(exp(cbind(OR=coef(cim_glm_domc), confint(cim_glm_domc))), Pvalue=summary(cim_glm_domc)$coefficients[,4]), 3)
round(cbind(exp(cbind(OR=coef(samoan_glm_domc), confint(samoan_glm_domc))), Pvalue=summary(samoan_glm_domc)$coefficients[,4]),3)
round(cbind(exp(cbind(OR=coef(tongan_glm_domc), confint(tongan_glm_domc))), Pvalue=summary(tongan_glm_domc)$coefficients[,4]),3)
```

# dom t
```{r domt}
cau_glm_domt=glm(as.factor(CAU$DIABETES) ~ as.factor(CAU$FULLCAUGTAFF)+CAU$BMI + CAU$AGECOL + as.factor(CAU$SEX.x) +  CAU$DOM_t, family="binomial")
nzm_glm_domt=glm( as.factor(nzm$DIABETES) ~ as.factor(nzm$FULLEPGTAFF) +nzm$BMI+ nzm$AGECOL + as.factor(nzm$SEX.x) + nzm$STANCESTRY+ nzm$DOM_t, family="binomial")
cim_glm_domt=glm(as.factor(cim$DIABETES)  ~ as.factor(cim$FULLEPGTAFF)+cim$BMI + cim$AGECOL + as.factor(cim$SEX.x) + cim$STANCESTRY+ cim$DOM_t, family="binomial")
samoan_glm_domt=glm(as.factor(samoan$DIABETES) ~ as.factor(samoan$FULLWPGTAFF) +samoan$BMI+ samoan$AGECOL + as.factor(samoan$SEX.x) + samoan$STANCESTRY+ samoan$DOM_t, family="binomial")
tongan_glm_domt=glm(as.factor(tongan$DIABETES)  ~ as.factor(tongan$FULLWPGTAFF)+ tongan$BMI+ tongan$AGECOL + as.factor(tongan$SEX.x) + tongan$STANCESTRY+ tongan$DOM_t, family="binomial")

round(cbind(exp(cbind(OR= coef(cau_glm_domt), confint(cau_glm_domt))),Pvalue= summary(cau_glm_domt)$coefficients[,4]),3)
round(cbind(exp(cbind(OR=coef(nzm_glm_domt), confint(nzm_glm_domt))), Pvalue=summary(nzm_glm_domt)$coefficients[,4]), 3)
round(cbind(exp(cbind(OR=coef(cim_glm_domt), confint(cim_glm_domt))), Pvalue=summary(cim_glm_domt)$coefficients[,4]), 3)
round(cbind(exp(cbind(OR=coef(samoan_glm_domt), confint(samoan_glm_domt))), Pvalue=summary(samoan_glm_domt)$coefficients[,4]),3)
round(cbind(exp(cbind(OR=coef(tongan_glm_domt), confint(tongan_glm_domt))), Pvalue=summary(tongan_glm_domt)$coefficients[,4]),3)
```

## domt male
```{r domt male}
cau_glm_domt=glm(as.factor(DIABETES) ~ as.factor(FULLCAUGTAFF)+BMI + AGECOL + DOM_t, family="binomial", data = CAU[CAU$SEX.x ==1, ])
nzm_glm_domt=glm( as.factor(DIABETES) ~ as.factor(FULLEPGTAFF) +BMI+ AGECOL + STANCESTRY+ DOM_t, family="binomial", data = nzm[nzm$SEX.x ==1, ])
cim_glm_domt=glm(as.factor(DIABETES)  ~ as.factor(FULLEPGTAFF)+BMI + AGECOL + STANCESTRY+ DOM_t, family="binomial", data = cim[cim$SEX.x ==1,])
samoan_glm_domt=glm(as.factor(DIABETES) ~ as.factor(FULLWPGTAFF) + BMI+ AGECOL + STANCESTRY+ DOM_t, family="binomial", data = samoan[samoan$SEX.x ==1,])
tongan_glm_domt=glm(as.factor(DIABETES)  ~ as.factor(FULLWPGTAFF)+ BMI+ AGECOL + STANCESTRY+ DOM_t, family="binomial", data = tongan[tongan$SEX.x ==1,])

round(cbind(exp(cbind(OR= coef(cau_glm_domt), confint(cau_glm_domt))),Pvalue= summary(cau_glm_domt)$coefficients[,4]),3)
round(cbind(exp(cbind(OR=coef(nzm_glm_domt), confint(nzm_glm_domt))), Pvalue=summary(nzm_glm_domt)$coefficients[,4]), 3)
round(cbind(exp(cbind(OR=coef(cim_glm_domt), confint(cim_glm_domt))), Pvalue=summary(cim_glm_domt)$coefficients[,4]), 3)
round(cbind(exp(cbind(OR=coef(samoan_glm_domt), confint(samoan_glm_domt))), Pvalue=summary(samoan_glm_domt)$coefficients[,4]),3)
round(cbind(exp(cbind(OR=coef(tongan_glm_domt), confint(tongan_glm_domt))), Pvalue=summary(tongan_glm_domt)$coefficients[,4]),3)
```

## domt female
```{r domt female}
cau_glm_domt=glm(as.factor(DIABETES) ~ as.factor(FULLCAUGTAFF)+BMI + AGECOL + DOM_t, family="binomial", data = CAU[CAU$SEX.x ==2, ])
nzm_glm_domt=glm( as.factor(DIABETES) ~ as.factor(FULLEPGTAFF) +BMI+ AGECOL + STANCESTRY+ DOM_t, family="binomial", data = nzm[nzm$SEX.x ==2, ])
cim_glm_domt=glm(as.factor(DIABETES)  ~ as.factor(FULLEPGTAFF)+BMI + AGECOL + STANCESTRY+ DOM_t, family="binomial", data = cim[cim$SEX.x ==2,])
samoan_glm_domt=glm(as.factor(DIABETES) ~ as.factor(FULLWPGTAFF) + BMI+ AGECOL + STANCESTRY+ DOM_t, family="binomial", data = samoan[samoan$SEX.x ==2,])
tongan_glm_domt=glm(as.factor(DIABETES)  ~ as.factor(FULLWPGTAFF)+ BMI+ AGECOL + STANCESTRY+ DOM_t, family="binomial", data = tongan[tongan$SEX.x ==2,])

round(cbind(exp(cbind(OR= coef(cau_glm_domt), confint(cau_glm_domt))),Pvalue= summary(cau_glm_domt)$coefficients[,4]),3)
round(cbind(exp(cbind(OR=coef(nzm_glm_domt), confint(nzm_glm_domt))), Pvalue=summary(nzm_glm_domt)$coefficients[,4]), 3)
round(cbind(exp(cbind(OR=coef(cim_glm_domt), confint(cim_glm_domt))), Pvalue=summary(cim_glm_domt)$coefficients[,4]), 3)
round(cbind(exp(cbind(OR=coef(samoan_glm_domt), confint(samoan_glm_domt))), Pvalue=summary(samoan_glm_domt)$coefficients[,4]),3)
round(cbind(exp(cbind(OR=coef(tongan_glm_domt), confint(tongan_glm_domt))), Pvalue=summary(tongan_glm_domt)$coefficients[,4]),3)
```

# het adv
```{r het}
cau_glm_het_adv=glm(as.factor(CAU$DIABETES) ~ as.factor(CAU$FULLCAUGTAFF)+CAU$BMI + CAU$AGECOL + as.factor(CAU$SEX.x) +  CAU$het_adv, family="binomial")
nzm_glm_het_adv=glm( as.factor(nzm$DIABETES) ~ as.factor(nzm$FULLEPGTAFF) +nzm$BMI+ nzm$AGECOL + as.factor(nzm$SEX.x) + nzm$STANCESTRY+ nzm$het_adv, family="binomial")
cim_glm_het_adv=glm(as.factor(cim$DIABETES)  ~ as.factor(cim$FULLEPGTAFF)+cim$BMI + cim$AGECOL + as.factor(cim$SEX.x) + cim$STANCESTRY+ cim$het_adv, family="binomial")
samoan_glm_het_adv=glm(as.factor(samoan$DIABETES) ~ as.factor(samoan$FULLWPGTAFF) +samoan$BMI+ samoan$AGECOL + as.factor(samoan$SEX.x) + samoan$STANCESTRY+ samoan$het_adv, family="binomial")
tongan_glm_het_adv=glm(as.factor(tongan$DIABETES)  ~ as.factor(tongan$FULLWPGTAFF)+ tongan$BMI+ tongan$AGECOL + as.factor(tongan$SEX.x) + tongan$STANCESTRY+ tongan$het_adv, family="binomial")

round(cbind(exp(cbind(OR= coef(cau_glm_het_adv), confint(cau_glm_het_adv))),Pvalue= summary(cau_glm_het_adv)$coefficients[,4]),3)
round(cbind(exp(cbind(OR=coef(nzm_glm_het_adv), confint(nzm_glm_het_adv))), Pvalue=summary(nzm_glm_het_adv)$coefficients[,4]), 3)
round(cbind(exp(cbind(OR=coef(cim_glm_het_adv), confint(cim_glm_het_adv))), Pvalue=summary(cim_glm_het_adv)$coefficients[,4]), 3)
round(cbind(exp(cbind(OR=coef(samoan_glm_het_adv), confint(samoan_glm_het_adv))), Pvalue=summary(samoan_glm_het_adv)$coefficients[,4]),3)
round(cbind(exp(cbind(OR=coef(tongan_glm_het_adv), confint(tongan_glm_het_adv))), Pvalue=summary(tongan_glm_het_adv)$coefficients[,4]),3)
```

## het male
```{r het male}
cau_glm_het_adv=glm(as.factor(DIABETES) ~ as.factor(FULLCAUGTAFF)+BMI + AGECOL + het_adv, family="binomial", data = CAU[CAU$SEX.x ==1,])
nzm_glm_het_adv=glm( as.factor(DIABETES) ~ as.factor(FULLEPGTAFF) +BMI+ AGECOL + STANCESTRY+ het_adv, family="binomial", data = nzm[nzm$SEX.x ==1,])
cim_glm_het_adv=glm(as.factor(DIABETES)  ~ as.factor(FULLEPGTAFF)+BMI + AGECOL + STANCESTRY+ het_adv, family="binomial", data = cim[cim$SEX.x ==1,])
samoan_glm_het_adv=glm(as.factor(DIABETES) ~ as.factor(FULLWPGTAFF) +BMI+ AGECOL + STANCESTRY+ het_adv, family="binomial", data = samoan[samoan$SEX.x ==1,])
tongan_glm_het_adv=glm(as.factor(DIABETES)  ~ as.factor(FULLWPGTAFF)+ BMI+ AGECOL + STANCESTRY+ het_adv, family="binomial", data = tongan[tongan$SEX.x ==1,])

round(cbind(exp(cbind(OR= coef(cau_glm_het_adv), confint(cau_glm_het_adv))),Pvalue= summary(cau_glm_het_adv)$coefficients[,4]),3)
round(cbind(exp(cbind(OR=coef(nzm_glm_het_adv), confint(nzm_glm_het_adv))), Pvalue=summary(nzm_glm_het_adv)$coefficients[,4]), 3)
round(cbind(exp(cbind(OR=coef(cim_glm_het_adv), confint(cim_glm_het_adv))), Pvalue=summary(cim_glm_het_adv)$coefficients[,4]), 3)
round(cbind(exp(cbind(OR=coef(samoan_glm_het_adv), confint(samoan_glm_het_adv))), Pvalue=summary(samoan_glm_het_adv)$coefficients[,4]),3)
round(cbind(exp(cbind(OR=coef(tongan_glm_het_adv), confint(tongan_glm_het_adv))), Pvalue=summary(tongan_glm_het_adv)$coefficients[,4]),3)
```

## het female
```{r het female}
cau_glm_het_adv=glm(as.factor(DIABETES) ~ as.factor(FULLCAUGTAFF)+BMI + AGECOL + het_adv, family="binomial", data = CAU[CAU$SEX.x ==2,])
nzm_glm_het_adv=glm( as.factor(DIABETES) ~ as.factor(FULLEPGTAFF) +BMI+ AGECOL + STANCESTRY+ het_adv, family="binomial", data = nzm[nzm$SEX.x ==2,])
cim_glm_het_adv=glm(as.factor(DIABETES)  ~ as.factor(FULLEPGTAFF)+BMI + AGECOL + STANCESTRY+ het_adv, family="binomial", data = cim[cim$SEX.x ==2,])
samoan_glm_het_adv=glm(as.factor(DIABETES) ~ as.factor(FULLWPGTAFF) +BMI+ AGECOL + STANCESTRY+ het_adv, family="binomial", data = samoan[samoan$SEX.x ==2,])
tongan_glm_het_adv=glm(as.factor(DIABETES)  ~ as.factor(FULLWPGTAFF)+ BMI+ AGECOL + STANCESTRY+ het_adv, family="binomial", data = tongan[tongan$SEX.x ==2,])

round(cbind(exp(cbind(OR= coef(cau_glm_het_adv), confint(cau_glm_het_adv))),Pvalue= summary(cau_glm_het_adv)$coefficients[,4]),3)
round(cbind(exp(cbind(OR=coef(nzm_glm_het_adv), confint(nzm_glm_het_adv))), Pvalue=summary(nzm_glm_het_adv)$coefficients[,4]), 3)
round(cbind(exp(cbind(OR=coef(cim_glm_het_adv), confint(cim_glm_het_adv))), Pvalue=summary(cim_glm_het_adv)$coefficients[,4]), 3)
round(cbind(exp(cbind(OR=coef(samoan_glm_het_adv), confint(samoan_glm_het_adv))), Pvalue=summary(samoan_glm_het_adv)$coefficients[,4]),3)
round(cbind(exp(cbind(OR=coef(tongan_glm_het_adv), confint(tongan_glm_het_adv))), Pvalue=summary(tongan_glm_het_adv)$coefficients[,4]),3)
```