# Murray Cadzow
# May 2014

#merged_haploped_pheno_gt=read.csv("~/Documents/PPARGC1A//merged_haploped_pheno_gt.txt", header=TRUE, sep="\t")
merged_haploped_pheno_gt=read.csv("~/Documents/PPARGC1A/Analysis/pheno_gt_ato_g.csv", header=TRUE, sep="\t")
merged_haploped_pheno_gt$DOM_c =ifelse( merged_haploped_pheno_gt$RS8192678_CC1_CT2_TT3 ==1 | merged_haploped_pheno_gt$RS8192678_CC1_CT2_TT3 ==2 , 1, 0)
merged_haploped_pheno_gt$DOM_t =ifelse( merged_haploped_pheno_gt$RS8192678_CC1_CT2_TT3 ==3 | merged_haploped_pheno_gt$RS8192678_CC1_CT2_TT3 ==2 , 1, 0)
merged_haploped_pheno_gt$het_adv =ifelse( merged_haploped_pheno_gt$RS8192678_CC1_CT2_TT3 ==2 , 1, 0)

cases=subset(merged_haploped_pheno_gt, merged_haploped_pheno_gt$GOUTAFFSTAT==2)
controls=subset(merged_haploped_pheno_gt, merged_haploped_pheno_gt$GOUTAFFSTAT==1)
nzm=subset(merged_haploped_pheno_gt, merged_haploped_pheno_gt$ETHNICITY=="1.0 NZ Maori")
nzm_c=subset(nzm, nzm$FULLEPGTAFF==1)
nzm_g=subset(nzm, nzm$FULLEPGTAFF==2)

samoan=subset(merged_haploped_pheno_gt, merged_haploped_pheno_gt$ETHNICITY=="1.0 Samoan")
samoan_g=subset(samoan, samoan$FULLWPGTAFF==2)
samoan_c=subset(samoan, samoan$FULLWPGTAFF==1)

tongan=subset(merged_haploped_pheno_gt, merged_haploped_pheno_gt$ETHNICITY=="1.0 Tongan")
tongan_c=subset(tongan,tongan$FULLWPGTAFF==1)
tongan_g=subset(tongan, tongan$FULLWPGTAFF==2)

cim=subset(merged_haploped_pheno_gt, merged_haploped_pheno_gt$ETHNICITY=="1.0 CI Maori")
cim_c=subset(cim, cim$FULLEPGTAFF==1)
cim_g=subset(cim, cim$FULLEPGTAFF==2)

merged_haploped_pheno_gt$ETHNICITY[merged_haploped_pheno_gt$ETHNICITY == "1.0 Caucasain"] = "1.0 Caucasian"

##CAU groups
CAU=subset(merged_haploped_pheno_gt, merged_haploped_pheno_gt$FULLCAUGTAFF==1 | merged_haploped_pheno_gt$FULLCAUGTAFF==2)
CAU_g=subset(CAU, CAU$FULLCAUGTAFF==2)
CAU_c=subset(CAU, CAU$FULLCAUGTAFF==1)

## EP groups
EP=subset(merged_haploped_pheno_gt, merged_haploped_pheno_gt$FULLEPGTAFF==1 | merged_haploped_pheno_gt$FULLEPGTAFF==2)

EPN=subset(EP, EP$EPNEPZ==1)
EPN_c=subset(EPN, EPN$FULLEPGTAFF==1)
EPN_g=subset(EPN, EPN$FULLEPGTAFF==2)

EPZ=subset(EP,EP$EPNEPZ==2)
EPZ_c=subset(EPZ, EPZ$FULLEPGTAFF==1)
EPZ_g=subset(EPZ, EPZ$FULLEPGTAFF==2)

EPWP=subset(merged_haploped_pheno_gt, merged_haploped_pheno_gt$FULLEPWPGTAFF==1 | merged_haploped_pheno_gt$FULLEPWPGTAFF==2)
EPWP_c=subset(EPWP, EPWP$FULLEPWPGTAFF==1)
EPWP_g=subset(EPWP, EPWP$FULLEPWPGTAFF==2)

## WP groups
WP=subset(merged_haploped_pheno_gt, merged_haploped_pheno_gt$FULLWPGTAFF==1 | merged_haploped_pheno_gt$FULLWPGTAFF==2)
WP_c=subset(WP, WP$FULLWPGTAFF==1)
WP_g=subset(WP, WP$FULLWPGTAFF==2)

CAU_mod=CAU
CAU_mod$STANCESTRY=rep(0, length(CAU_mod[,1]))
CAU_mod=CAU_mod[c("FULLCAUGTAFF", "DIABETES", "STANCESTRY", "SEX.x","AGECOL", "BMI", "RS8192678_CC1_CT2_TT3", "DOM_c","DOM_t", "het_adv")]
colnames(CAU_mod) = c("FULLGTAFF", "DIABETES", "STANCESTRY", "SEX.x","AGECOL", "BMI", "RS8192678_CC1_CT2_TT3", "DOM_c","DOM_t", "het_adv")
CAU_mod$POP=rep("CAU", length(CAU_mod[,1]))

EPN_mod=EPN[c("FULLEPGTAFF", "DIABETES", "STANCESTRY", "SEX.x","AGECOL", "BMI", "RS8192678_CC1_CT2_TT3", "DOM_c","DOM_t", "het_adv")]
colnames(EPN_mod) = c("FULLGTAFF", "DIABETES", "STANCESTRY", "SEX.x","AGECOL", "BMI", "RS8192678_CC1_CT2_TT3", "DOM_c","DOM_t", "het_adv")
EPN_mod$POP = rep("EPN", length(EPN_mod[,1]))

EPZ_mod=EPZ[c("FULLEPGTAFF", "DIABETES", "STANCESTRY", "SEX.x","AGECOL", "BMI", "RS8192678_CC1_CT2_TT3", "DOM_c","DOM_t", "het_adv")]
colnames(EPZ_mod) = c("FULLGTAFF", "DIABETES", "STANCESTRY", "SEX.x","AGECOL", "BMI", "RS8192678_CC1_CT2_TT3", "DOM_c","DOM_t", "het_adv")
EPZ_mod$POP = rep("EPZ", length(EPZ_mod[,1]))

WP_mod=WP[c("FULLWPGTAFF", "DIABETES", "STANCESTRY", "SEX.x","AGECOL", "BMI", "RS8192678_CC1_CT2_TT3", "DOM_c","DOM_t", "het_adv")]
colnames(WP_mod) = c("FULLGTAFF", "DIABETES", "STANCESTRY", "SEX.x","AGECOL", "BMI", "RS8192678_CC1_CT2_TT3", "DOM_c","DOM_t", "het_adv")
WP_mod$POP = rep("WP", length(WP_mod[,1]))

EPWP_mod= EPWP[c("FULLEPWPGTAFF", "DIABETES", "STANCESTRY", "SEX.x","AGECOL", "BMI", "RS8192678_CC1_CT2_TT3", "DOM_c","DOM_t", "het_adv")]
colnames(EPWP_mod) = c("FULLGTAFF", "DIABETES", "STANCESTRY", "SEX.x","AGECOL", "BMI", "RS8192678_CC1_CT2_TT3", "DOM_c","DOM_t", "het_adv")
EPWP_mod$POP = rep("EPWP", length(EPWP_mod[,1]))

combined_all = rbind(CAU_mod, EPN_mod, EPZ_mod, WP_mod, EPWP_mod)
combined_poly = rbind(EPN_mod, EPZ_mod, WP_mod, EPWP_mod)

combined_poly_glm_additive = glm(as.factor(combined_poly$DIABETES) ~ as.factor(combined_poly$FULLGTAFF) + combined_poly$BMI + combined_poly$STANCESTRY +  as.factor(combined_poly$SEX.x) + combined_poly$AGECOL + as.factor(combined_poly$POP) * combined_poly$RS8192678_CC1_CT2_TT3, family="binomial")
combined_poly_glm_domc = glm(as.factor(combined_poly$DIABETES) ~ as.factor(combined_poly$FULLGTAFF) + combined_poly$BMI + combined_poly$STANCESTRY +  as.factor(combined_poly$SEX.x) + combined_poly$AGECOL + as.factor(combined_poly$POP) * combined_poly$DOM_c, family="binomial")
combined_poly_glm_domt = glm(as.factor(combined_poly$DIABETES) ~ as.factor(combined_poly$FULLGTAFF) + combined_poly$BMI + combined_poly$STANCESTRY +  as.factor(combined_poly$SEX.x) + combined_poly$AGECOL + as.factor(combined_poly$POP) * combined_poly$DOM_t, family="binomial")
combined_poly_glm_het_adv = glm(as.factor(combined_poly$DIABETES) ~ as.factor(combined_poly$FULLGTAFF) + combined_poly$BMI + combined_poly$STANCESTRY +  as.factor(combined_poly$SEX.x) + combined_poly$AGECOL + as.factor(combined_poly$POP) * combined_poly$het_adv, family="binomial")

# summary(combined_poly_glm_additive)
# summary(combined_poly_glm_domc)
# summary(combined_poly_glm_domt)
# summary(combined_poly_glm_het_adv)


combined_all_glm_additive = glm(as.factor(combined_all$DIABETES) ~ as.factor(combined_all$FULLGTAFF) + combined_all$BMI + combined_all$STANCESTRY +  as.factor(combined_all$SEX.x) + combined_all$AGECOL + as.factor(combined_all$POP) * combined_all$RS8192678_CC1_CT2_TT3, family="binomial")
combined_all_glm_domc = glm(as.factor(combined_all$DIABETES) ~ as.factor(combined_all$FULLGTAFF) + combined_all$BMI + combined_all$STANCESTRY +  as.factor(combined_all$SEX.x) + combined_all$AGECOL + as.factor(combined_all$POP) * combined_all$DOM_c, family="binomial")
combined_all_glm_domt = glm(as.factor(combined_all$DIABETES) ~ as.factor(combined_all$FULLGTAFF) + combined_all$BMI + combined_all$STANCESTRY +  as.factor(combined_all$SEX.x) + combined_all$AGECOL + as.factor(combined_all$POP) * combined_all$DOM_t, family="binomial")
combined_all_glm_het_adv = glm(as.factor(combined_all$DIABETES) ~ as.factor(combined_all$FULLGTAFF) + combined_all$BMI + combined_all$STANCESTRY +  as.factor(combined_all$SEX.x) + combined_all$AGECOL + as.factor(combined_all$POP) * combined_all$het_adv, family="binomial")

# summary(combined_all_glm_additive)
# summary(combined_all_glm_domc)
# summary(combined_all_glm_domt)
# summary(combined_all_glm_het_adv)


diabetes_regression=function(group){
  a= glm(as.factor(group$DIABETES)  ~ as.factor(group$FULLWPGTAFF) +group$BMI+ group$AGECOL + as.factor(group$SEX.x) + group$STANCESTRY+ group$RS8192678_CC1_CT2_TT3, family="binomial")
  return(a)
}


#################################################
## regressions ADDITIVE MODEL ##################
##############################################

cau_glm_additive=glm(as.factor(CAU$DIABETES) ~ as.factor(CAU$FULLCAUGTAFF)+CAU$BMI + CAU$AGECOL + as.factor(CAU$SEX.x) +  CAU$RS8192678_CC1_CT2_TT3, family="binomial")
cau_g_glm_additive=glm( as.factor(CAU_g$DIABETES)  ~ CAU_g$BMI + CAU_g$AGECOL + as.factor(CAU_g$SEX.x) +  CAU_g$RS8192678_CC1_CT2_TT3, family="binomial")
cau_c_glm_additive=glm( as.factor(CAU_c$DIABETES)~ CAU_c$BMI + CAU_c$AGECOL + as.factor(CAU_c$SEX.x) +   CAU_c$RS8192678_CC1_CT2_TT3, family="binomial")

wp_glm_additive=glm(as.factor(WP$DIABETES) ~ as.factor(WP$FULLWPGTAFF) +WP$BMI+ WP$AGECOL + as.factor(WP$SEX.x) + WP$STANCESTRY+ WP$RS8192678_CC1_CT2_TT3, family="binomial")
wp_g_glm_additive=glm( as.factor(WP_g$DIABETES) ~WP_g$BMI+ WP_g$AGECOL + as.factor(WP_g$SEX.x) +WP_g$STANCESTRY+ WP_g$RS8192678_CC1_CT2_TT3, family="binomial")
wp_c_glm_additive=glm(as.factor(WP_c$DIABETES) ~WP_c$BMI + WP_c$AGECOL + as.factor(WP_c$SEX.x) + WP_c$STANCESTRY+ WP_c$RS8192678_CC1_CT2_TT3, family="binomial")

epn_glm_additive=glm( as.factor(EPN$DIABETES) ~ as.factor(EPN$FULLEPGTAFF) +EPN$BMI+ EPN$AGECOL + as.factor(EPN$SEX.x) + EPN$STANCESTRY + EPN$RS8192678_CC1_CT2_TT3, family="binomial")
epn_g_glm_additive=glm(as.factor(EPN_g$DIABETES) ~ EPN_g$BMI + EPN_g$AGECOL + as.factor(EPN_g$SEX.x) + EPN_g$STANCESTRY + EPN_g$RS8192678_CC1_CT2_TT3, family="binomial")
epn_c_glm_additive=glm(as.factor(EPN_c$DIABETES) ~EPN_c$BMI + EPN_c$AGECOL + as.factor(EPN_c$SEX.x) +  +EPN_c$STANCESTRY + EPN_c$RS8192678_CC1_CT2_TT3, family="binomial")

epz_glm_additive=glm(as.factor(EPZ$DIABETES) ~ as.factor(EPZ$FULLEPGTAFF)+EPZ$BMI + EPZ$AGECOL + as.factor(EPZ$SEX.x) +  EPZ$STANCESTRY + EPZ$RS8192678_CC1_CT2_TT3, family="binomial")
epz_g_glm_additive=glm(as.factor(EPZ_g$DIABETES) ~ EPZ_g$BMI+ EPZ_g$AGECOL + as.factor(EPZ_g$SEX.x) +  EPZ_g$STANCESTRY + EPZ_g$RS8192678_CC1_CT2_TT3, family="binomial")
epz_c_glm_additive=glm(as.factor(EPZ_c$DIABETES) ~EPZ_c$BMI + EPZ_c$AGECOL + as.factor(EPZ_c$SEX.x) + EPZ_c$STANCESTRY + EPZ_c$RS8192678_CC1_CT2_TT3, family="binomial")

epwp_glm_additive=glm( as.factor(EPWP$DIABETES) ~ as.factor(EPWP$FULLEPWPGTAFF) +EPWP$BMI+ EPWP$AGECOL + as.factor(EPWP$SEX.x) + EPWP$STANCESTRY + EPWP$RS8192678_CC1_CT2_TT3, family="binomial")
epwp_g_glm_additive=glm(as.factor(EPWP_g$DIABETES) ~EPWP_g$BMI+ EPWP_g$AGECOL + as.factor(EPWP_g$SEX.x) + EPWP_g$STANCESTRY + EPWP_g$RS8192678_CC1_CT2_TT3, family="binomial")
epwp_c_glm_additive=glm( as.factor(EPWP_c$DIABETES) ~ EPWP_c$BMI+ EPWP_c$AGECOL + as.factor(EPWP_c$SEX.x) + EPWP_c$STANCESTRY + EPWP_c$RS8192678_CC1_CT2_TT3, family="binomial")


nzm_glm_additive=glm( as.factor(nzm$DIABETES) ~ as.factor(nzm$FULLEPGTAFF) +nzm$BMI+ nzm$AGECOL + as.factor(nzm$SEX.x) + nzm$STANCESTRY+ nzm$RS8192678_CC1_CT2_TT3, family="binomial")
nzm_g_glm_additive=glm(as.factor(nzm_g$DIABETES)  ~ nzm_g$BMI + nzm_g$AGECOL + as.factor(nzm_g$SEX.x) + nzm_g$STANCESTRY+ nzm_g$RS8192678_CC1_CT2_TT3, family="binomial")
nzm_c_glm_additive=glm(as.factor(nzm_c$DIABETES)  ~ nzm_c$BMI+ nzm_c$AGECOL + as.factor(nzm_c$SEX.x) + nzm_c$STANCESTRY+ nzm_c$RS8192678_CC1_CT2_TT3, family="binomial")

cim_glm_additive=glm(as.factor(cim$DIABETES)  ~ as.factor(cim$FULLEPGTAFF)+cim$BMI + cim$AGECOL + as.factor(cim$SEX.x) + cim$STANCESTRY+ cim$RS8192678_CC1_CT2_TT3, family="binomial")
cim_g_glm_additive=glm(as.factor(cim_g$DIABETES) ~cim_g$BMI+  cim_g$AGECOL + as.factor(cim_g$SEX.x) + cim_g$STANCESTRY+ cim_g$RS8192678_CC1_CT2_TT3, family="binomial")
cim_c_glm_additive=glm(as.factor(cim_c$DIABETES) ~cim_c$BMI+ cim_c$AGECOL + as.factor(cim_c$SEX.x) +cim_c$STANCESTRY+ cim_c$RS8192678_CC1_CT2_TT3, family="binomial")

samoan_glm_additive=glm(as.factor(samoan$DIABETES) ~ as.factor(samoan$FULLWPGTAFF) +samoan$BMI+ samoan$AGECOL + as.factor(samoan$SEX.x) + samoan$STANCESTRY+ samoan$RS8192678_CC1_CT2_TT3, family="binomial")
samoan_g_glm_additive=glm(as.factor(samoan_g$DIABETES) ~samoan_g$BMI+ samoan_g$AGECOL + as.factor(samoan_g$SEX.x) + samoan_g$STANCESTRY+ samoan_g$RS8192678_CC1_CT2_TT3, family="binomial")
samoan_c_glm_additive=glm(as.factor(samoan_c$DIABETES) ~samoan_c$BMI + samoan_c$AGECOL + as.factor(samoan_c$SEX.x) +samoan_c$STANCESTRY+ samoan_c$RS8192678_CC1_CT2_TT3, family="binomial")

tongan_glm_additive=glm(as.factor(tongan$DIABETES)  ~ as.factor(tongan$FULLWPGTAFF)+ tongan$BMI+ tongan$AGECOL + as.factor(tongan$SEX.x) + tongan$STANCESTRY+ tongan$RS8192678_CC1_CT2_TT3, family="binomial")
tongan_g_glm_additive=glm(as.factor(tongan_g$DIABETES)  ~tongan_g$BMI+ tongan_g$AGECOL + as.factor(tongan_g$SEX.x) + tongan_g$STANCESTRY+ tongan_g$RS8192678_CC1_CT2_TT3, family="binomial")
tongan_c_glm_additive=glm(as.factor(tongan_c$DIABETES)  ~tongan_c$BMI+ tongan_c$AGECOL + as.factor(tongan_c$SEX.x) + tongan_c$STANCESTRY+ tongan_c$RS8192678_CC1_CT2_TT3, family="binomial")

sink(file="diabetes_additive_model_OR.txt")
summary(cau_glm_additive)
# summary(cau_c_glm_additive)
# summary(cau_g_glm_additive)
# summary(epn_glm_additive)
# summary(epn_c_glm_additive)
# summary(epn_g_glm_additive)
# summary(epz_glm_additive)
# summary(epz_c_glm_additive)
# summary(epz_g_glm_additive)
# summary(wp_glm_additive)
# summary(wp_c_glm_additive)
# summary(wp_g_glm_additive)
# summary(epwp_glm_additive)
# summary(epwp_c_glm_additive)
# summary(epwp_g_glm_additive)
summary(nzm_glm_additive)
# summary(nzm_c_glm_additive)
# summary(nzm_g_glm_additive)
summary(cim_glm_additive)
# summary(cim_c_glm_additive)
# summary(cim_g_glm_additive)
summary(samoan_glm_additive)
# summary(samoan_c_glm_additive)
# summary(samoan_g_glm_additive)
summary(tongan_glm_additive)
# summary(tongan_c_glm_additive)
# summary(tongan_g_glm_additive)
# summary(combined_poly_glm_additive)
# summary(combined_all_glm_additive)
confint(cau_glm_additive)
# confint(cau_c_glm_additive)
# confint(cau_g_glm_additive)
# confint(epn_glm_additive)
# confint(epn_c_glm_additive)
# confint(epn_g_glm_additive)
# confint(epz_glm_additive)
# confint(epz_c_glm_additive)
# confint(epz_g_glm_additive)
# confint(wp_glm_additive)
# confint(wp_c_glm_additive)
# confint(wp_g_glm_additive)
# confint(epwp_glm_additive)
# confint(epwp_c_glm_additive)
# confint(epwp_g_glm_additive)
confint(nzm_glm_additive)
# confint(nzm_c_glm_additive)
# confint(nzm_g_glm_additive)
confint(cim_glm_additive)
# confint(cim_c_glm_additive)
# confint(cim_g_glm_additive)
confint(samoan_glm_additive)
# confint(samoan_c_glm_additive)
# confint(samoan_g_glm_additive)
confint(tongan_glm_additive)
# confint(tongan_c_glm_additive)
# confint(tongan_g_glm_additive)
# confint(combined_poly_glm_additive)
# confint(combined_all_glm_additive)
round(cbind(exp(cbind(OR= coef(cau_glm_additive), confint(cau_glm_additive))),Pvalue= summary(cau_glm_additive)$coefficients[,4]),3)
# confint(epn_glm_additive)
# confint(epz_glm_additive)
# confint(wp_glm_additive)
# confint(epwp_glm_additive)
round(cbind(exp(cbind(OR=coef(nzm_glm_additive), confint(nzm_glm_additive))), Pvalue=summary(nzm_glm_additive)$coefficients[,4]), 3)
round(cbind(exp(cbind(OR=coef(cim_glm_additive), confint(cim_glm_additive))), Pvalue=summary(cim_glm_additive)$coefficients[,4]), 3)
round(cbind(exp(cbind(OR=coef(samoan_glm_additive), confint(samoan_glm_additive))), Pvalue=summary(samoan_glm_additive)$coefficients[,4]),3)
round(cbind(exp(cbind(OR=coef(tongan_glm_additive), confint(tongan_glm_additive))), Pvalue=summary(tongan_glm_additive)$coefficients[,4]),3)
round(cbind(exp(cbind(OR=coef(combined_poly_glm_additive), confint(combined_poly_glm_additive))), Pvalue=summary(combined_poly_glm_additive)$coefficients[,4]),3)
round(cbind(exp(cbind(OR=coef(combined_all_glm_additive), confint(combined_all_glm_additive))), Pvalue=summary(combined_all_glm_additive)$coefficients[,4]),3)
sink()

additive_table=function(x){write.table(x, file="diabetes_additive_table_OR.csv",sep="\t", quote=FALSE, append=TRUE)}
#additive_table(summary(cau_glm_additive)$coefficients)
#additive_table(summary(cau_c_glm_additive)$coefficients)
#additive_table(summary(cau_g_glm_additive)$coefficients)
#additive_table(summary(epn_glm_additive)$coefficients)
#additive_table(summary(epn_c_glm_additive)$coefficients)
#additive_table(summary(epn_g_glm_additive)$coefficients)
#additive_table(summary(epz_glm_additive)$coefficients)
#additive_table(summary(epz_c_glm_additive)$coefficients)
#additive_table(summary(epz_g_glm_additive)$coefficients)
#additive_table(summary(wp_glm_additive)$coefficients)
#additive_table(summary(wp_c_glm_additive)$coefficients)
#additive_table(summary(wp_g_glm_additive)$coefficients)
#additive_table(summary(epwp_glm_additive)$coefficients)
#additive_table(summary(epwp_c_glm_additive)$coefficients)
#additive_table(summary(epwp_g_glm_additive)$coefficients)
#additive_table(summary(nzm_glm_additive)$coefficients)
#additive_table(summary(nzm_c_glm_additive)$coefficients)
#additive_table(summary(nzm_g_glm_additive)$coefficients)
#additive_table(summary(cim_glm_additive)$coefficients)
#additive_table(summary(cim_c_glm_additive)$coefficients)
#additive_table(summary(cim_g_glm_additive)$coefficients)
#additive_table(summary(samoan_glm_additive)$coefficients)
#additive_table(summary(samoan_c_glm_additive)$coefficients)
#additive_table(summary(samoan_g_glm_additive)$coefficients)
#additive_table(summary(tongan_glm_additive)$coefficients)
#additive_table(summary(tongan_c_glm_additive)$coefficients)
#additive_table(summary(tongan_g_glm_additive)$coefficients)
#additive_table(summary(combined_poly_glm_additive)$coefficients)
#additive_table(summary(combined_all_glm_additive)$coefficients)
#additive_table(confint(cau_glm_additive))
#additive_table(confint(cau_c_glm_additive))
#additive_table(confint(cau_g_glm_additive))
#additive_table(confint(epn_glm_additive))
#additive_table(confint(epn_c_glm_additive))
#additive_table(confint(epn_g_glm_additive))
#additive_table(confint(epz_glm_additive))
#additive_table(confint(epz_c_glm_additive))
#additive_table(confint(epz_g_glm_additive))
#additive_table(confint(wp_glm_additive))
#additive_table(confint(wp_c_glm_additive))
#additive_table(confint(wp_g_glm_additive))
#additive_table(confint(epwp_glm_additive))
#additive_table(confint(epwp_c_glm_additive))
#additive_table(confint(epwp_g_glm_additive))
#additive_table(confint(nzm_glm_additive))
#additive_table(confint(nzm_c_glm_additive))
#additive_table(confint(nzm_g_glm_additive))
#additive_table(confint(cim_glm_additive))
#additive_table(confint(cim_c_glm_additive))
#additive_table(confint(cim_g_glm_additive))
#additive_table(confint(samoan_glm_additive))
#additive_table(confint(samoan_c_glm_additive))
#additive_table(confint(samoan_g_glm_additive))
#additive_table(confint(tongan_glm_additive))
#additive_table(confint(tongan_c_glm_additive))
#additive_table(confint(tongan_g_glm_additive))
#additive_table(confint(combined_poly_glm_additive))
#additive_table(confint(combined_all_glm_additive))
additive_table(round(cbind(exp(cbind(OR= coef(cau_glm_additive), confint(cau_glm_additive))),Pvalue= summary(cau_glm_additive)$coefficients[,4]),3))
additive_table(round(cbind(exp(cbind(OR=coef(nzm_glm_additive), confint(nzm_glm_additive))), Pvalue=summary(nzm_glm_additive)$coefficients[,4]),3))
additive_table(round(cbind(exp(cbind(OR=coef(cim_glm_additive), confint(cim_glm_additive))), Pvalue=summary(cim_glm_additive)$coefficients[,4]),3))
additive_table(round(cbind(exp(cbind(OR=coef(samoan_glm_additive), confint(samoan_glm_additive))), Pvalue=summary(samoan_glm_additive)$coefficients[,4]),3))
additive_table(round(cbind(exp(cbind(OR=coef(tongan_glm_additive), confint(tongan_glm_additive))), Pvalue=summary(tongan_glm_additive)$coefficients[,4]),3))
additive_table(round(cbind(exp(cbind(OR=coef(combined_poly_glm_additive), confint(combined_poly_glm_additive))), Pvalue=summary(combined_poly_glm_additive)$coefficients[,4]),3))
additive_table(round(cbind(exp(cbind(OR=coef(combined_all_glm_additive), confint(combined_all_glm_additive))), Pvalue=summary(combined_all_glm_additive)$coefficients[,4]),3))



#################################################
## regressions DOMINANT CC MODEL ###############
##############################################
cau_glm_domc=glm(as.factor(CAU$DIABETES) ~ as.factor(CAU$FULLCAUGTAFF)+CAU$BMI + CAU$AGECOL + as.factor(CAU$SEX.x) +  CAU$DOM_c, family="binomial")
cau_g_glm_domc=glm( as.factor(CAU_g$DIABETES)  ~ CAU_g$BMI + CAU_g$AGECOL + as.factor(CAU_g$SEX.x) +  CAU_g$DOM_c, family="binomial")
cau_c_glm_domc=glm( as.factor(CAU_c$DIABETES)~ CAU_c$BMI + CAU_c$AGECOL + as.factor(CAU_c$SEX.x) +   CAU_c$DOM_c, family="binomial")

wp_glm_domc=glm(as.factor(WP$DIABETES) ~ as.factor(WP$FULLWPGTAFF) +WP$BMI+ WP$AGECOL + as.factor(WP$SEX.x) + WP$STANCESTRY+ WP$DOM_c, family="binomial")
wp_g_glm_domc=glm( as.factor(WP_g$DIABETES) ~WP_g$BMI+ WP_g$AGECOL + as.factor(WP_g$SEX.x) +WP_g$STANCESTRY+ WP_g$DOM_c, family="binomial")
wp_c_glm_domc=glm(as.factor(WP_c$DIABETES) ~WP_c$BMI + WP_c$AGECOL + as.factor(WP_c$SEX.x) + WP_c$STANCESTRY+ WP_c$DOM_c, family="binomial")

epn_glm_domc=glm( as.factor(EPN$DIABETES) ~ as.factor(EPN$FULLEPGTAFF) +EPN$BMI+ EPN$AGECOL + as.factor(EPN$SEX.x) + EPN$STANCESTRY + EPN$DOM_c, family="binomial")
epn_g_glm_domc=glm(as.factor(EPN_g$DIABETES) ~ EPN_g$BMI + EPN_g$AGECOL + as.factor(EPN_g$SEX.x) + EPN_g$STANCESTRY + EPN_g$DOM_c, family="binomial")
epn_c_glm_domc=glm(as.factor(EPN_c$DIABETES) ~EPN_c$BMI + EPN_c$AGECOL + as.factor(EPN_c$SEX.x) +  +EPN_c$STANCESTRY + EPN_c$DOM_c, family="binomial")

epz_glm_domc=glm(as.factor(EPZ$DIABETES) ~ as.factor(EPZ$FULLEPGTAFF)+EPZ$BMI + EPZ$AGECOL + as.factor(EPZ$SEX.x) +  EPZ$STANCESTRY + EPZ$DOM_c, family="binomial")
epz_g_glm_domc=glm(as.factor(EPZ_g$DIABETES) ~ EPZ_g$BMI+ EPZ_g$AGECOL + as.factor(EPZ_g$SEX.x) +  EPZ_g$STANCESTRY + EPZ_g$DOM_c, family="binomial")
epz_c_glm_domc=glm(as.factor(EPZ_c$DIABETES) ~EPZ_c$BMI + EPZ_c$AGECOL + as.factor(EPZ_c$SEX.x) + EPZ_c$STANCESTRY + EPZ_c$DOM_c, family="binomial")

epwp_glm_domc=glm( as.factor(EPWP$DIABETES) ~ as.factor(EPWP$FULLEPWPGTAFF) +EPWP$BMI+ EPWP$AGECOL + as.factor(EPWP$SEX.x) + EPWP$STANCESTRY + EPWP$DOM_c, family="binomial")
epwp_g_glm_domc=glm(as.factor(EPWP_g$DIABETES) ~EPWP_g$BMI+ EPWP_g$AGECOL + as.factor(EPWP_g$SEX.x) + EPWP_g$STANCESTRY + EPWP_g$DOM_c, family="binomial")
epwp_c_glm_domc=glm( as.factor(EPWP_c$DIABETES) ~ EPWP_c$BMI+ EPWP_c$AGECOL + as.factor(EPWP_c$SEX.x) + EPWP_c$STANCESTRY + EPWP_c$DOM_c, family="binomial")


nzm_glm_domc=glm( as.factor(nzm$DIABETES) ~ as.factor(nzm$FULLEPGTAFF) +nzm$BMI+ nzm$AGECOL + as.factor(nzm$SEX.x) + nzm$STANCESTRY+ nzm$DOM_c, family="binomial")
nzm_g_glm_domc=glm(as.factor(nzm_g$DIABETES)  ~ nzm_g$BMI + nzm_g$AGECOL + as.factor(nzm_g$SEX.x) + nzm_g$STANCESTRY+ nzm_g$DOM_c, family="binomial")
nzm_c_glm_domc=glm(as.factor(nzm_c$DIABETES)  ~ nzm_c$BMI+ nzm_c$AGECOL + as.factor(nzm_c$SEX.x) + nzm_c$STANCESTRY+ nzm_c$DOM_c, family="binomial")

cim_glm_domc=glm(as.factor(cim$DIABETES)  ~ as.factor(cim$FULLEPGTAFF)+cim$BMI + cim$AGECOL + as.factor(cim$SEX.x) + cim$STANCESTRY+ cim$DOM_c, family="binomial")
cim_g_glm_domc=glm(as.factor(cim_g$DIABETES) ~cim_g$BMI+  cim_g$AGECOL + as.factor(cim_g$SEX.x) + cim_g$STANCESTRY+ cim_g$DOM_c, family="binomial")
cim_c_glm_domc=glm(as.factor(cim_c$DIABETES) ~cim_c$BMI+ cim_c$AGECOL + as.factor(cim_c$SEX.x) +cim_c$STANCESTRY+ cim_c$DOM_c, family="binomial")

samoan_glm_domc=glm(as.factor(samoan$DIABETES) ~ as.factor(samoan$FULLWPGTAFF) +samoan$BMI+ samoan$AGECOL + as.factor(samoan$SEX.x) + samoan$STANCESTRY+ samoan$DOM_c, family="binomial")
samoan_g_glm_domc=glm(as.factor(samoan_g$DIABETES) ~samoan_g$BMI+ samoan_g$AGECOL + as.factor(samoan_g$SEX.x) + samoan_g$STANCESTRY+ samoan_g$DOM_c, family="binomial")
samoan_c_glm_domc=glm(as.factor(samoan_c$DIABETES) ~samoan_c$BMI + samoan_c$AGECOL + as.factor(samoan_c$SEX.x) +samoan_c$STANCESTRY+ samoan_c$DOM_c, family="binomial")

tongan_glm_domc=glm(as.factor(tongan$DIABETES)  ~ as.factor(tongan$FULLWPGTAFF)+ tongan$BMI+ tongan$AGECOL + as.factor(tongan$SEX.x) + tongan$STANCESTRY+ tongan$DOM_c, family="binomial")
tongan_g_glm_domc=glm(as.factor(tongan_g$DIABETES)  ~tongan_g$BMI+ tongan_g$AGECOL + as.factor(tongan_g$SEX.x) + tongan_g$STANCESTRY+ tongan_g$DOM_c, family="binomial")
tongan_c_glm_domc=glm(as.factor(tongan_c$DIABETES)  ~tongan_c$BMI+ tongan_c$AGECOL + as.factor(tongan_c$SEX.x) + tongan_c$STANCESTRY+ tongan_c$DOM_c, family="binomial")



sink(file="diabetes_dominant_CC_model_OR.txt")
#summary(cau_glm_domc)
#summary(cau_c_glm_domc)
#summary(cau_g_glm_domc)
#summary(epn_glm_domc)
#summary(epn_c_glm_domc)
#summary(epn_g_glm_domc)
#summary(epz_glm_domc)
#summary(epz_c_glm_domc)
#summary(epz_g_glm_domc)
#summary(wp_glm_domc)
#summary(wp_c_glm_domc)
#summary(wp_g_glm_domc)
#summary(epwp_glm_domc)
#summary(epwp_c_glm_domc)
#summary(epwp_g_glm_domc)
#summary(nzm_glm_domc)
#summary(nzm_c_glm_domc)
#summary(nzm_g_glm_domc)
#summary(cim_glm_domc)
#summary(cim_c_glm_domc)
#summary(cim_g_glm_domc)
#summary(samoan_glm_domc)
#summary(samoan_c_glm_domc)
#summary(samoan_g_glm_domc)
#summary(tongan_glm_domc)
#summary(tongan_c_glm_domc)
#summary(tongan_g_glm_domc)
#summary(combined_poly_glm_domc)
#summary(combined_all_glm_domc)
#confint(cau_glm_domc)
#confint(cau_c_glm_domc)
#confint(cau_g_glm_domc)
#confint(epn_glm_domc)
#confint(epn_c_glm_domc)
#confint(epn_g_glm_domc)
#confint(epz_glm_domc)
#confint(epz_c_glm_domc)
#confint(epz_g_glm_domc)
#confint(wp_glm_domc)
#confint(wp_c_glm_domc)
#confint(wp_g_glm_domc)
#confint(epwp_glm_domc)
#confint(epwp_c_glm_domc)
#confint(epwp_g_glm_domc)
#confint(nzm_glm_domc)
#confint(nzm_c_glm_domc)
#confint(nzm_g_glm_domc)
#confint(cim_glm_domc)
#confint(cim_c_glm_domc)
#confint(cim_g_glm_domc)
#confint(samoan_glm_domc)
#confint(samoan_c_glm_domc)
#confint(samoan_g_glm_domc)
#confint(tongan_glm_domc)
#confint(tongan_c_glm_domc)
#confint(tongan_g_glm_domc)
#confint(combined_poly_glm_domc)
#confint(combined_all_glm_domc)
round(cbind(exp(cbind(OR= coef(cau_glm_domc), confint(cau_glm_domc))),Pvalue= summary(cau_glm_domc)$coefficients[,4]),3)
# confint(epn_glm_domc)
# confint(epz_glm_domc)
# confint(wp_glm_domc)
# confint(epwp_glm_domc)
round(cbind(exp(cbind(OR=coef(nzm_glm_domc), confint(nzm_glm_domc))), Pvalue=summary(nzm_glm_domc)$coefficients[,4]), 3)
round(cbind(exp(cbind(OR=coef(cim_glm_domc), confint(cim_glm_domc))), Pvalue=summary(cim_glm_domc)$coefficients[,4]), 3)
round(cbind(exp(cbind(OR=coef(samoan_glm_domc), confint(samoan_glm_domc))), Pvalue=summary(samoan_glm_domc)$coefficients[,4]),3)
round(cbind(exp(cbind(OR=coef(tongan_glm_domc), confint(tongan_glm_domc))), Pvalue=summary(tongan_glm_domc)$coefficients[,4]),3)
round(cbind(exp(cbind(OR=coef(combined_poly_glm_domc), confint(combined_poly_glm_domc))), Pvalue=summary(combined_poly_glm_domc)$coefficients[,4]),3)
round(cbind(exp(cbind(OR=coef(combined_all_glm_domc), confint(combined_all_glm_domc))), Pvalue=summary(combined_all_glm_domc)$coefficients[,4]),3)
sink()

domc_table=function(x){write.table(x, file="diabetes_domc_table_OR.csv",sep="\t", quote=FALSE, append=TRUE)}
#domc_table(summary(cau_glm_domc)$coefficients)
#domc_table(summary(cau_c_glm_domc)$coefficients)
#domc_table(summary(cau_g_glm_domc)$coefficients)
#domc_table(summary(epn_glm_domc)$coefficients)
#domc_table(summary(epn_c_glm_domc)$coefficients)
#domc_table(summary(epn_g_glm_domc)$coefficients)
#domc_table(summary(epz_glm_domc)$coefficients)
#domc_table(summary(epz_c_glm_domc)$coefficients)
#domc_table(summary(epz_g_glm_domc)$coefficients)
#domc_table(summary(wp_glm_domc)$coefficients)
#domc_table(summary(wp_c_glm_domc)$coefficients)
#domc_table(summary(wp_g_glm_domc)$coefficients)
#domc_table(summary(epwp_glm_domc)$coefficients)
#domc_table(summary(epwp_c_glm_domc)$coefficients)
#domc_table(summary(epwp_g_glm_domc)$coefficients)
#domc_table(summary(nzm_glm_domc)$coefficients)
#domc_table(summary(nzm_c_glm_domc)$coefficients)
#domc_table(summary(nzm_g_glm_domc)$coefficients)
#domc_table(summary(cim_glm_domc)$coefficients)
#domc_table(summary(cim_c_glm_domc)$coefficients)
#domc_table(summary(cim_g_glm_domc)$coefficients)
#domc_table(summary(samoan_glm_domc)$coefficients)
#domc_table(summary(samoan_c_glm_domc)$coefficients)
#domc_table(summary(samoan_g_glm_domc)$coefficients)
#domc_table(summary(tongan_glm_domc)$coefficients)
#domc_table(summary(tongan_c_glm_domc)$coefficients)
#domc_table(summary(tongan_g_glm_domc)$coefficients)
#domc_table(summary(combined_poly_glm_domc)$coefficients)
#domc_table(summary(combined_all_glm_domc)$coefficients)
#domc_table(confint(cau_glm_domc))
#domc_table(confint(cau_c_glm_domc))
#domc_table(confint(cau_g_glm_domc))
#domc_table(confint(epn_glm_domc))
#domc_table(confint(epn_c_glm_domc))
#domc_table(confint(epn_g_glm_domc))
#domc_table(confint(epz_glm_domc))
#domc_table(confint(epz_c_glm_domc))
#domc_table(confint(epz_g_glm_domc))
#domc_table(confint(wp_glm_domc))
#domc_table(confint(wp_c_glm_domc))
#domc_table(confint(wp_g_glm_domc))
#domc_table(confint(epwp_glm_domc))
#domc_table(confint(epwp_c_glm_domc))
#domc_table(confint(epwp_g_glm_domc))
#domc_table(confint(nzm_glm_domc))
#domc_table(confint(nzm_c_glm_domc))
#domc_table(confint(nzm_g_glm_domc))
#domc_table(confint(cim_glm_domc))
#domc_table(confint(cim_c_glm_domc))
#domc_table(confint(cim_g_glm_domc))
#domc_table(confint(samoan_glm_domc))
#domc_table(confint(samoan_c_glm_domc))
#domc_table(confint(samoan_g_glm_domc))
#domc_table(confint(tongan_glm_domc))
#domc_table(confint(tongan_c_glm_domc))
#domc_table(confint(tongan_g_glm_domc))
#domc_table(confint(combined_poly_glm_domc))
#domc_table(confint(combined_all_glm_domc))
domc_table(round(cbind(exp(cbind(OR= coef(cau_glm_domc), confint(cau_glm_domc))),Pvalue= summary(cau_glm_domc)$coefficients[,4]),3))
domc_table(round(cbind(exp(cbind(OR=coef(nzm_glm_domc), confint(nzm_glm_domc))), Pvalue=summary(nzm_glm_domc)$coefficients[,4]),3))
domc_table(round(cbind(exp(cbind(OR=coef(cim_glm_domc), confint(cim_glm_domc))), Pvalue=summary(cim_glm_domc)$coefficients[,4]),3))
domc_table(round(cbind(exp(cbind(OR=coef(samoan_glm_domc), confint(samoan_glm_domc))), Pvalue=summary(samoan_glm_domc)$coefficients[,4]),3))
domc_table(round(cbind(exp(cbind(OR=coef(tongan_glm_domc), confint(tongan_glm_domc))), Pvalue=summary(tongan_glm_domc)$coefficients[,4]),3))
domc_table(round(cbind(exp(cbind(OR=coef(combined_poly_glm_domc), confint(combined_poly_glm_domc))), Pvalue=summary(combined_poly_glm_domc)$coefficients[,4]),3))
domc_table(round(cbind(exp(cbind(OR=coef(combined_all_glm_domc), confint(combined_all_glm_domc))), Pvalue=summary(combined_all_glm_domc)$coefficients[,4]),3))


#################################################
## regressions DOMINANT TT MODEL ###############
##############################################
cau_glm_domt=glm(as.factor(CAU$DIABETES) ~ as.factor(CAU$FULLCAUGTAFF)+CAU$BMI + CAU$AGECOL + as.factor(CAU$SEX.x) +  CAU$DOM_t, family="binomial")
cau_g_glm_domt=glm( as.factor(CAU_g$DIABETES)  ~ CAU_g$BMI + CAU_g$AGECOL + as.factor(CAU_g$SEX.x) +  CAU_g$DOM_t, family="binomial")
cau_c_glm_domt=glm( as.factor(CAU_c$DIABETES)~ CAU_c$BMI + CAU_c$AGECOL + as.factor(CAU_c$SEX.x) +   CAU_c$DOM_t, family="binomial")

wp_glm_domt=glm(as.factor(WP$DIABETES) ~ as.factor(WP$FULLWPGTAFF) +WP$BMI+ WP$AGECOL + as.factor(WP$SEX.x) + WP$STANCESTRY+ WP$DOM_t, family="binomial")
wp_g_glm_domt=glm( as.factor(WP_g$DIABETES) ~WP_g$BMI+ WP_g$AGECOL + as.factor(WP_g$SEX.x) +WP_g$STANCESTRY+ WP_g$DOM_t, family="binomial")
wp_c_glm_domt=glm(as.factor(WP_c$DIABETES) ~WP_c$BMI + WP_c$AGECOL + as.factor(WP_c$SEX.x) + WP_c$STANCESTRY+ WP_c$DOM_t, family="binomial")

epn_glm_domt=glm( as.factor(EPN$DIABETES) ~ as.factor(EPN$FULLEPGTAFF) +EPN$BMI+ EPN$AGECOL + as.factor(EPN$SEX.x) + EPN$STANCESTRY + EPN$DOM_t, family="binomial")
epn_g_glm_domt=glm(as.factor(EPN_g$DIABETES) ~ EPN_g$BMI + EPN_g$AGECOL + as.factor(EPN_g$SEX.x) + EPN_g$STANCESTRY + EPN_g$DOM_t, family="binomial")
epn_c_glm_domt=glm(as.factor(EPN_c$DIABETES) ~EPN_c$BMI + EPN_c$AGECOL + as.factor(EPN_c$SEX.x) +  +EPN_c$STANCESTRY + EPN_c$DOM_t, family="binomial")

epz_glm_domt=glm(as.factor(EPZ$DIABETES) ~ as.factor(EPZ$FULLEPGTAFF)+EPZ$BMI + EPZ$AGECOL + as.factor(EPZ$SEX.x) +  EPZ$STANCESTRY + EPZ$DOM_t, family="binomial")
epz_g_glm_domt=glm(as.factor(EPZ_g$DIABETES) ~ EPZ_g$BMI+ EPZ_g$AGECOL + as.factor(EPZ_g$SEX.x) +  EPZ_g$STANCESTRY + EPZ_g$DOM_t, family="binomial")
epz_c_glm_domt=glm(as.factor(EPZ_c$DIABETES) ~EPZ_c$BMI + EPZ_c$AGECOL + as.factor(EPZ_c$SEX.x) + EPZ_c$STANCESTRY + EPZ_c$DOM_t, family="binomial")

epwp_glm_domt=glm( as.factor(EPWP$DIABETES) ~ as.factor(EPWP$FULLEPWPGTAFF) +EPWP$BMI+ EPWP$AGECOL + as.factor(EPWP$SEX.x) + EPWP$STANCESTRY + EPWP$DOM_t, family="binomial")
epwp_g_glm_domt=glm(as.factor(EPWP_g$DIABETES) ~EPWP_g$BMI+ EPWP_g$AGECOL + as.factor(EPWP_g$SEX.x) + EPWP_g$STANCESTRY + EPWP_g$DOM_t, family="binomial")
epwp_c_glm_domt=glm( as.factor(EPWP_c$DIABETES) ~ EPWP_c$BMI+ EPWP_c$AGECOL + as.factor(EPWP_c$SEX.x) + EPWP_c$STANCESTRY + EPWP_c$DOM_t, family="binomial")


nzm_glm_domt=glm( as.factor(nzm$DIABETES) ~ as.factor(nzm$FULLEPGTAFF) +nzm$BMI+ nzm$AGECOL + as.factor(nzm$SEX.x) + nzm$STANCESTRY+ nzm$DOM_t, family="binomial")
nzm_g_glm_domt=glm(as.factor(nzm_g$DIABETES)  ~ nzm_g$BMI + nzm_g$AGECOL + as.factor(nzm_g$SEX.x) + nzm_g$STANCESTRY+ nzm_g$DOM_t, family="binomial")
nzm_c_glm_domt=glm(as.factor(nzm_c$DIABETES)  ~ nzm_c$BMI+ nzm_c$AGECOL + as.factor(nzm_c$SEX.x) + nzm_c$STANCESTRY+ nzm_c$DOM_t, family="binomial")

cim_glm_domt=glm(as.factor(cim$DIABETES)  ~ as.factor(cim$FULLEPGTAFF)+cim$BMI + cim$AGECOL + as.factor(cim$SEX.x) + cim$STANCESTRY+ cim$DOM_t, family="binomial")
cim_g_glm_domt=glm(as.factor(cim_g$DIABETES) ~cim_g$BMI+  cim_g$AGECOL + as.factor(cim_g$SEX.x) + cim_g$STANCESTRY+ cim_g$DOM_t, family="binomial")
cim_c_glm_domt=glm(as.factor(cim_c$DIABETES) ~cim_c$BMI+ cim_c$AGECOL + as.factor(cim_c$SEX.x) +cim_c$STANCESTRY+ cim_c$DOM_t, family="binomial")

samoan_glm_domt=glm(as.factor(samoan$DIABETES) ~ as.factor(samoan$FULLWPGTAFF) +samoan$BMI+ samoan$AGECOL + as.factor(samoan$SEX.x) + samoan$STANCESTRY+ samoan$DOM_t, family="binomial")
samoan_g_glm_domt=glm(as.factor(samoan_g$DIABETES) ~samoan_g$BMI+ samoan_g$AGECOL + as.factor(samoan_g$SEX.x) + samoan_g$STANCESTRY+ samoan_g$DOM_t, family="binomial")
samoan_c_glm_domt=glm(as.factor(samoan_c$DIABETES) ~samoan_c$BMI + samoan_c$AGECOL + as.factor(samoan_c$SEX.x) +samoan_c$STANCESTRY+ samoan_c$DOM_t, family="binomial")

tongan_glm_domt=glm(as.factor(tongan$DIABETES)  ~ as.factor(tongan$FULLWPGTAFF)+ tongan$BMI+ tongan$AGECOL + as.factor(tongan$SEX.x) + tongan$STANCESTRY+ tongan$DOM_t, family="binomial")
tongan_g_glm_domt=glm(as.factor(tongan_g$DIABETES)  ~tongan_g$BMI+ tongan_g$AGECOL + as.factor(tongan_g$SEX.x) + tongan_g$STANCESTRY+ tongan_g$DOM_t, family="binomial")
tongan_c_glm_domt=glm(as.factor(tongan_c$DIABETES)  ~tongan_c$BMI+ tongan_c$AGECOL + as.factor(tongan_c$SEX.x) + tongan_c$STANCESTRY+ tongan_c$DOM_t, family="binomial")



sink(file="diabetes_dominant_TT_model_OR.txt")
#summary(cau_glm_domt)
#summary(cau_c_glm_domt)
#summary(cau_g_glm_domt)
#summary(epn_glm_domt)
#summary(epn_c_glm_domt)
#summary(epn_g_glm_domt)
#summary(epz_glm_domt)
#summary(epz_c_glm_domt)
#summary(epz_g_glm_domt)
#summary(wp_glm_domt)
#summary(wp_c_glm_domt)
#summary(wp_g_glm_domt)
#summary(epwp_glm_domt)
#summary(epwp_c_glm_domt)
#summary(epwp_g_glm_domt)
#summary(nzm_glm_domt)
#summary(nzm_c_glm_domt)
#summary(nzm_g_glm_domt)
#summary(cim_glm_domt)
#summary(cim_c_glm_domt)
#summary(cim_g_glm_domt)
#summary(samoan_glm_domt)
#summary(samoan_c_glm_domt)
#summary(samoan_g_glm_domt)
#summary(tongan_glm_domt)
#summary(tongan_c_glm_domt)
#summary(tongan_g_glm_domt)
#summary(combined_poly_glm_domt)
#summary(combined_all_glm_domt)
#confint(cau_glm_domt)
#confint(cau_c_glm_domt)
#confint(cau_g_glm_domt)
#confint(epn_glm_domt)
#confint(epn_c_glm_domt)
#confint(epn_g_glm_domt)
#confint(epz_glm_domt)
#confint(epz_c_glm_domt)
#confint(epz_g_glm_domt)
#confint(wp_glm_domt)
#confint(wp_c_glm_domt)
#confint(wp_g_glm_domt)
#confint(epwp_glm_domt)
#confint(epwp_c_glm_domt)
#confint(epwp_g_glm_domt)
#confint(nzm_glm_domt)
#confint(nzm_c_glm_domt)
#confint(nzm_g_glm_domt)
#confint(cim_glm_domt)
#confint(cim_c_glm_domt)
#confint(cim_g_glm_domt)
#confint(samoan_glm_domt)
#confint(samoan_c_glm_domt)
#confint(samoan_g_glm_domt)
#confint(tongan_glm_domt)
#confint(tongan_c_glm_domt)
#confint(tongan_g_glm_domt)
#confint(combined_poly_glm_domt)
#confint(combined_all_glm_domt)

round(cbind(exp(cbind(OR= coef(cau_glm_domt), confint(cau_glm_domt))),Pvalue= summary(cau_glm_domt)$coefficients[,4]),3)
# confint(epn_glm_domt)
# confint(epz_glm_domt)
# confint(wp_glm_domt)
# confint(epwp_glm_domt)
round(cbind(exp(cbind(OR=coef(nzm_glm_domt), confint(nzm_glm_domt))), Pvalue=summary(nzm_glm_domt)$coefficients[,4]), 3)
round(cbind(exp(cbind(OR=coef(cim_glm_domt), confint(cim_glm_domt))), Pvalue=summary(cim_glm_domt)$coefficients[,4]), 3)
round(cbind(exp(cbind(OR=coef(samoan_glm_domt), confint(samoan_glm_domt))), Pvalue=summary(samoan_glm_domt)$coefficients[,4]),3)
round(cbind(exp(cbind(OR=coef(tongan_glm_domt), confint(tongan_glm_domt))), Pvalue=summary(tongan_glm_domt)$coefficients[,4]),3)
round(cbind(exp(cbind(OR=coef(combined_poly_glm_domt), confint(combined_poly_glm_domt))), Pvalue=summary(combined_poly_glm_domt)$coefficients[,4]),3)
round(cbind(exp(cbind(OR=coef(combined_all_glm_domt), confint(combined_all_glm_domt))), Pvalue=summary(combined_all_glm_domt)$coefficients[,4]),3)
sink()

domt_table=function(x){write.table(x, file="diabetes_domt_table_OR.csv",sep="\t", quote=FALSE, append=TRUE)}
#domt_table(summary(cau_glm_domt)$coefficients)
#domt_table(summary(cau_c_glm_domt)$coefficients)
#domt_table(summary(cau_g_glm_domt)$coefficients)
#domt_table(summary(epn_glm_domt)$coefficients)
#domt_table(summary(epn_c_glm_domt)$coefficients)
#domt_table(summary(epn_g_glm_domt)$coefficients)
#domt_table(summary(epz_glm_domt)$coefficients)
#domt_table(summary(epz_c_glm_domt)$coefficients)
#domt_table(summary(epz_g_glm_domt)$coefficients)
#domt_table(summary(wp_glm_domt)$coefficients)
#domt_table(summary(wp_c_glm_domt)$coefficients)
#domt_table(summary(wp_g_glm_domt)$coefficients)
#domt_table(summary(epwp_glm_domt)$coefficients)
#domt_table(summary(epwp_c_glm_domt)$coefficients)
#domt_table(summary(epwp_g_glm_domt)$coefficients)
#domt_table(summary(nzm_glm_domt)$coefficients)
#domt_table(summary(nzm_c_glm_domt)$coefficients)
#domt_table(summary(nzm_g_glm_domt)$coefficients)
#domt_table(summary(cim_glm_domt)$coefficients)
#domt_table(summary(cim_c_glm_domt)$coefficients)
#domt_table(summary(cim_g_glm_domt)$coefficients)
#domt_table(summary(samoan_glm_domt)$coefficients)
#domt_table(summary(samoan_c_glm_domt)$coefficients)
#domt_table(summary(samoan_g_glm_domt)$coefficients)
#domt_table(summary(tongan_glm_domt)$coefficients)
#domt_table(summary(tongan_c_glm_domt)$coefficients)
#domt_table(summary(tongan_g_glm_domt)$coefficients)
#domt_table(summary(combined_poly_glm_domt)$coefficients)
#domt_table(summary(combined_all_glm_domt)$coefficients)
#domt_table(confint(cau_glm_domt))
#domt_table(confint(cau_c_glm_domt))
#domt_table(confint(cau_g_glm_domt))
#domt_table(confint(epn_glm_domt))
#domt_table(confint(epn_c_glm_domt))
#domt_table(confint(epn_g_glm_domt))
#domt_table(confint(epz_glm_domt))
#domt_table(confint(epz_c_glm_domt))
#domt_table(confint(epz_g_glm_domt))
#domt_table(confint(wp_glm_domt))
#domt_table(confint(wp_c_glm_domt))
#domt_table(confint(wp_g_glm_domt))
#domt_table(confint(epwp_glm_domt))
#domt_table(confint(epwp_c_glm_domt))
#domt_table(confint(epwp_g_glm_domt))
#domt_table(confint(nzm_glm_domt))
#domt_table(confint(nzm_c_glm_domt))
#domt_table(confint(nzm_g_glm_domt))
#domt_table(confint(cim_glm_domt))
#domt_table(confint(cim_c_glm_domt))
#domt_table(confint(cim_g_glm_domt))
#domt_table(confint(samoan_glm_domt))
#domt_table(confint(samoan_c_glm_domt))
#domt_table(confint(samoan_g_glm_domt))
#domt_table(confint(tongan_glm_domt))
#domt_table(confint(tongan_c_glm_domt))
#domt_table(confint(tongan_g_glm_domt))
#domt_table(confint(combined_poly_glm_domt))
#domt_table(confint(combined_all_glm_domt))
domt_table(round(cbind(exp(cbind(OR= coef(cau_glm_domt), confint(cau_glm_domt))),Pvalue= summary(cau_glm_domt)$coefficients[,4]),3))
domt_table(round(cbind(exp(cbind(OR=coef(nzm_glm_domt), confint(nzm_glm_domt))), Pvalue=summary(nzm_glm_domt)$coefficients[,4]),3))
domt_table(round(cbind(exp(cbind(OR=coef(cim_glm_domt), confint(cim_glm_domt))), Pvalue=summary(cim_glm_domt)$coefficients[,4]),3))
domt_table(round(cbind(exp(cbind(OR=coef(samoan_glm_domt), confint(samoan_glm_domt))), Pvalue=summary(samoan_glm_domt)$coefficients[,4]),3))
domt_table(round(cbind(exp(cbind(OR=coef(tongan_glm_domt), confint(tongan_glm_domt))), Pvalue=summary(tongan_glm_domt)$coefficients[,4]),3))
domt_table(round(cbind(exp(cbind(OR=coef(combined_poly_glm_domt), confint(combined_poly_glm_domt))), Pvalue=summary(combined_poly_glm_domt)$coefficients[,4]),3))
domt_table(round(cbind(exp(cbind(OR=coef(combined_all_glm_domt), confint(combined_all_glm_domt))), Pvalue=summary(combined_all_glm_domt)$coefficients[,4]),3))




#################################################
## regressions HET ADVANTAGE MODEL ###############
##############################################
cau_glm_het_adv=glm(as.factor(CAU$DIABETES) ~ as.factor(CAU$FULLCAUGTAFF)+CAU$BMI + CAU$AGECOL + as.factor(CAU$SEX.x) +  CAU$het_adv, family="binomial")
cau_g_glm_het_adv=glm( as.factor(CAU_g$DIABETES)  ~ CAU_g$BMI + CAU_g$AGECOL + as.factor(CAU_g$SEX.x) +  CAU_g$het_adv, family="binomial")
cau_c_glm_het_adv=glm( as.factor(CAU_c$DIABETES)~ CAU_c$BMI + CAU_c$AGECOL + as.factor(CAU_c$SEX.x) +   CAU_c$het_adv, family="binomial")

wp_glm_het_adv=glm(as.factor(WP$DIABETES) ~ as.factor(WP$FULLWPGTAFF) +WP$BMI+ WP$AGECOL + as.factor(WP$SEX.x) + WP$STANCESTRY+ WP$het_adv, family="binomial")
wp_g_glm_het_adv=glm( as.factor(WP_g$DIABETES) ~WP_g$BMI+ WP_g$AGECOL + as.factor(WP_g$SEX.x) +WP_g$STANCESTRY+ WP_g$het_adv, family="binomial")
wp_c_glm_het_adv=glm(as.factor(WP_c$DIABETES) ~WP_c$BMI + WP_c$AGECOL + as.factor(WP_c$SEX.x) + WP_c$STANCESTRY+ WP_c$het_adv, family="binomial")

epn_glm_het_adv=glm( as.factor(EPN$DIABETES) ~ as.factor(EPN$FULLEPGTAFF) +EPN$BMI+ EPN$AGECOL + as.factor(EPN$SEX.x) + EPN$STANCESTRY + EPN$het_adv, family="binomial")
epn_g_glm_het_adv=glm(as.factor(EPN_g$DIABETES) ~ EPN_g$BMI + EPN_g$AGECOL + as.factor(EPN_g$SEX.x) + EPN_g$STANCESTRY + EPN_g$het_adv, family="binomial")
epn_c_glm_het_adv=glm(as.factor(EPN_c$DIABETES) ~EPN_c$BMI + EPN_c$AGECOL + as.factor(EPN_c$SEX.x) +  +EPN_c$STANCESTRY + EPN_c$het_adv, family="binomial")

epz_glm_het_adv=glm(as.factor(EPZ$DIABETES) ~ as.factor(EPZ$FULLEPGTAFF)+EPZ$BMI + EPZ$AGECOL + as.factor(EPZ$SEX.x) +  EPZ$STANCESTRY + EPZ$het_adv, family="binomial")
epz_g_glm_het_adv=glm(as.factor(EPZ_g$DIABETES) ~ EPZ_g$BMI+ EPZ_g$AGECOL + as.factor(EPZ_g$SEX.x) +  EPZ_g$STANCESTRY + EPZ_g$het_adv, family="binomial")
epz_c_glm_het_adv=glm(as.factor(EPZ_c$DIABETES) ~EPZ_c$BMI + EPZ_c$AGECOL + as.factor(EPZ_c$SEX.x) + EPZ_c$STANCESTRY + EPZ_c$het_adv, family="binomial")

epwp_glm_het_adv=glm( as.factor(EPWP$DIABETES) ~ as.factor(EPWP$FULLEPWPGTAFF) +EPWP$BMI+ EPWP$AGECOL + as.factor(EPWP$SEX.x) + EPWP$STANCESTRY + EPWP$het_adv, family="binomial")
epwp_g_glm_het_adv=glm(as.factor(EPWP_g$DIABETES) ~EPWP_g$BMI+ EPWP_g$AGECOL + as.factor(EPWP_g$SEX.x) + EPWP_g$STANCESTRY + EPWP_g$het_adv, family="binomial")
epwp_c_glm_het_adv=glm( as.factor(EPWP_c$DIABETES) ~ EPWP_c$BMI+ EPWP_c$AGECOL + as.factor(EPWP_c$SEX.x) + EPWP_c$STANCESTRY + EPWP_c$het_adv, family="binomial")


nzm_glm_het_adv=glm( as.factor(nzm$DIABETES) ~ as.factor(nzm$FULLEPGTAFF) +nzm$BMI+ nzm$AGECOL + as.factor(nzm$SEX.x) + nzm$STANCESTRY+ nzm$het_adv, family="binomial")
nzm_g_glm_het_adv=glm(as.factor(nzm_g$DIABETES)  ~ nzm_g$BMI + nzm_g$AGECOL + as.factor(nzm_g$SEX.x) + nzm_g$STANCESTRY+ nzm_g$het_adv, family="binomial")
nzm_c_glm_het_adv=glm(as.factor(nzm_c$DIABETES)  ~ nzm_c$BMI+ nzm_c$AGECOL + as.factor(nzm_c$SEX.x) + nzm_c$STANCESTRY+ nzm_c$het_adv, family="binomial")

cim_glm_het_adv=glm(as.factor(cim$DIABETES)  ~ as.factor(cim$FULLEPGTAFF)+cim$BMI + cim$AGECOL + as.factor(cim$SEX.x) + cim$STANCESTRY+ cim$het_adv, family="binomial")
cim_g_glm_het_adv=glm(as.factor(cim_g$DIABETES) ~cim_g$BMI+  cim_g$AGECOL + as.factor(cim_g$SEX.x) + cim_g$STANCESTRY+ cim_g$het_adv, family="binomial")
cim_c_glm_het_adv=glm(as.factor(cim_c$DIABETES) ~cim_c$BMI+ cim_c$AGECOL + as.factor(cim_c$SEX.x) +cim_c$STANCESTRY+ cim_c$het_adv, family="binomial")

samoan_glm_het_adv=glm(as.factor(samoan$DIABETES) ~ as.factor(samoan$FULLWPGTAFF) +samoan$BMI+ samoan$AGECOL + as.factor(samoan$SEX.x) + samoan$STANCESTRY+ samoan$het_adv, family="binomial")
samoan_g_glm_het_adv=glm(as.factor(samoan_g$DIABETES) ~samoan_g$BMI+ samoan_g$AGECOL + as.factor(samoan_g$SEX.x) + samoan_g$STANCESTRY+ samoan_g$het_adv, family="binomial")
samoan_c_glm_het_adv=glm(as.factor(samoan_c$DIABETES) ~samoan_c$BMI + samoan_c$AGECOL + as.factor(samoan_c$SEX.x) +samoan_c$STANCESTRY+ samoan_c$het_adv, family="binomial")

tongan_glm_het_adv=glm(as.factor(tongan$DIABETES)  ~ as.factor(tongan$FULLWPGTAFF)+ tongan$BMI+ tongan$AGECOL + as.factor(tongan$SEX.x) + tongan$STANCESTRY+ tongan$het_adv, family="binomial")
tongan_g_glm_het_adv=glm(as.factor(tongan_g$DIABETES)  ~tongan_g$BMI+ tongan_g$AGECOL + as.factor(tongan_g$SEX.x) + tongan_g$STANCESTRY+ tongan_g$het_adv, family="binomial")
tongan_c_glm_het_adv=glm(as.factor(tongan_c$DIABETES)  ~tongan_c$BMI+ tongan_c$AGECOL + as.factor(tongan_c$SEX.x) + tongan_c$STANCESTRY+ tongan_c$het_adv, family="binomial")



sink(file="diabetes_het_adv_model_OR.txt")
#summary(cau_glm_het_adv)
#summary(cau_c_glm_het_adv)
#summary(cau_g_glm_het_adv)
#summary(epn_glm_het_adv)
#summary(epn_c_glm_het_adv)
#summary(epn_g_glm_het_adv)
#summary(epz_glm_het_adv)
#summary(epz_c_glm_het_adv)
#summary(epz_g_glm_het_adv)
#summary(wp_glm_het_adv)
#summary(wp_c_glm_het_adv)
#summary(wp_g_glm_het_adv)
#summary(epwp_glm_het_adv)
#summary(epwp_c_glm_het_adv)
#summary(epwp_g_glm_het_adv)
#summary(nzm_glm_het_adv)
#summary(nzm_c_glm_het_adv)
#summary(nzm_g_glm_het_adv)
#summary(cim_glm_het_adv)
#summary(cim_c_glm_het_adv)
#summary(cim_g_glm_het_adv)
#summary(samoan_glm_het_adv)
# summary(samoan_c_glm_het_adv)
# summary(samoan_g_glm_het_adv)
# summary(tongan_glm_het_adv)
# summary(tongan_c_glm_het_adv)
# summary(tongan_g_glm_het_adv)
# summary(combined_poly_glm_het_adv)
# summary(combined_all_glm_het_adv)
# confint(cau_glm_het_adv)
# confint(cau_c_glm_het_adv)
# confint(cau_g_glm_het_adv)
# confint(epn_glm_het_adv)
# confint(epn_c_glm_het_adv)
# confint(epn_g_glm_het_adv)
# confint(epz_glm_het_adv)
# confint(epz_c_glm_het_adv)
# confint(epz_g_glm_het_adv)
# confint(wp_glm_het_adv)
# confint(wp_c_glm_het_adv)
# confint(wp_g_glm_het_adv)
# confint(epwp_glm_het_adv)
# confint(epwp_c_glm_het_adv)
# confint(epwp_g_glm_het_adv)
# confint(nzm_glm_het_adv)
# confint(nzm_c_glm_het_adv)
# confint(nzm_g_glm_het_adv)
# confint(cim_glm_het_adv)
# confint(cim_c_glm_het_adv)
# confint(cim_g_glm_het_adv)
# confint(samoan_glm_het_adv)
# confint(samoan_c_glm_het_adv)
# confint(samoan_g_glm_het_adv)
# confint(tongan_glm_het_adv)
# confint(tongan_c_glm_het_adv)
# confint(tongan_g_glm_het_adv)
# confint(combined_poly_glm_het_adv)
# confint(combined_all_glm_het_adv)
round(cbind(exp(cbind(OR= coef(cau_glm_het_adv), confint(cau_glm_het_adv))),Pvalue= summary(cau_glm_het_adv)$coefficients[,4]),3)
# confint(epn_glm_het_adv)
# confint(epz_glm_het_adv)
# confint(wp_glm_het_adv)
# confint(epwp_glm_het_adv)
round(cbind(exp(cbind(OR=coef(nzm_glm_het_adv), confint(nzm_glm_het_adv))), Pvalue=summary(nzm_glm_het_adv)$coefficients[,4]), 3)
round(cbind(exp(cbind(OR=coef(cim_glm_het_adv), confint(cim_glm_het_adv))), Pvalue=summary(cim_glm_het_adv)$coefficients[,4]), 3)
round(cbind(exp(cbind(OR=coef(samoan_glm_het_adv), confint(samoan_glm_het_adv))), Pvalue=summary(samoan_glm_het_adv)$coefficients[,4]),3)
round(cbind(exp(cbind(OR=coef(tongan_glm_het_adv), confint(tongan_glm_het_adv))), Pvalue=summary(tongan_glm_het_adv)$coefficients[,4]),3)
round(cbind(exp(cbind(OR=coef(combined_poly_glm_het_adv), confint(combined_poly_glm_het_adv))), Pvalue=summary(combined_poly_glm_het_adv)$coefficients[,4]),3)
round(cbind(exp(cbind(OR=coef(combined_all_glm_het_adv), confint(combined_all_glm_het_adv))), Pvalue=summary(combined_all_glm_het_adv)$coefficients[,4]),3)
sink()

het_adv_table=function(x){write.table(x, file="diabetes_het_adv_table_OR.csv",sep="\t", quote=FALSE, append=TRUE)}
# het_adv_table(summary(cau_glm_het_adv)$coefficients)
# het_adv_table(summary(cau_c_glm_het_adv)$coefficients)
# het_adv_table(summary(cau_g_glm_het_adv)$coefficients)
# het_adv_table(summary(epn_glm_het_adv)$coefficients)
# het_adv_table(summary(epn_c_glm_het_adv)$coefficients)
# het_adv_table(summary(epn_g_glm_het_adv)$coefficients)
# het_adv_table(summary(epz_glm_het_adv)$coefficients)
# het_adv_table(summary(epz_c_glm_het_adv)$coefficients)
# het_adv_table(summary(epz_g_glm_het_adv)$coefficients)
# het_adv_table(summary(wp_glm_het_adv)$coefficients)
# het_adv_table(summary(wp_c_glm_het_adv)$coefficients)
# het_adv_table(summary(wp_g_glm_het_adv)$coefficients)
# het_adv_table(summary(epwp_glm_het_adv)$coefficients)
# het_adv_table(summary(epwp_c_glm_het_adv)$coefficients)
# het_adv_table(summary(epwp_g_glm_het_adv)$coefficients)
# het_adv_table(summary(nzm_glm_het_adv)$coefficients)
# het_adv_table(summary(nzm_c_glm_het_adv)$coefficients)
# het_adv_table(summary(nzm_g_glm_het_adv)$coefficients)
# het_adv_table(summary(cim_glm_het_adv)$coefficients)
# het_adv_table(summary(cim_c_glm_het_adv)$coefficients)
# het_adv_table(summary(cim_g_glm_het_adv)$coefficients)
# het_adv_table(summary(samoan_glm_het_adv)$coefficients)
# het_adv_table(summary(samoan_c_glm_het_adv)$coefficients)
# het_adv_table(summary(samoan_g_glm_het_adv)$coefficients)
# het_adv_table(summary(tongan_glm_het_adv)$coefficients)
# het_adv_table(summary(tongan_c_glm_het_adv)$coefficients)
# het_adv_table(summary(tongan_g_glm_het_adv)$coefficients)
# het_adv_table(summary(combined_poly_glm_het_adv)$coefficients)
# het_adv_table(summary(combined_all_glm_het_adv)$coefficients)
# het_adv_table(confint(cau_glm_het_adv))
# het_adv_table(confint(cau_c_glm_het_adv))
# het_adv_table(confint(cau_g_glm_het_adv))
# het_adv_table(confint(epn_glm_het_adv))
# het_adv_table(confint(epn_c_glm_het_adv))
# het_adv_table(confint(epn_g_glm_het_adv))
# het_adv_table(confint(epz_glm_het_adv))
# het_adv_table(confint(epz_c_glm_het_adv))
# het_adv_table(confint(epz_g_glm_het_adv))
# het_adv_table(confint(wp_glm_het_adv))
# het_adv_table(confint(wp_c_glm_het_adv))
# het_adv_table(confint(wp_g_glm_het_adv))
# het_adv_table(confint(epwp_glm_het_adv))
# het_adv_table(confint(epwp_c_glm_het_adv))
# het_adv_table(confint(epwp_g_glm_het_adv))
# het_adv_table(confint(nzm_glm_het_adv))
# het_adv_table(confint(nzm_c_glm_het_adv))
# het_adv_table(confint(nzm_g_glm_het_adv))
# het_adv_table(confint(cim_glm_het_adv))
# het_adv_table(confint(cim_c_glm_het_adv))
# het_adv_table(confint(cim_g_glm_het_adv))
# het_adv_table(confint(samoan_glm_het_adv))
# het_adv_table(confint(samoan_c_glm_het_adv))
# het_adv_table(confint(samoan_g_glm_het_adv))
# het_adv_table(confint(tongan_glm_het_adv))
# het_adv_table(confint(tongan_c_glm_het_adv))
# het_adv_table(confint(tongan_g_glm_het_adv))
# het_adv_table(confint(combined_poly_glm_het_adv))
# het_adv_table(confint(combined_all_glm_het_adv))
het_adv_table(round(cbind(exp(cbind(OR= coef(cau_glm_het_adv), confint(cau_glm_het_adv))),Pvalue= summary(cau_glm_het_adv)$coefficients[,4]),3))
het_adv_table(round(cbind(exp(cbind(OR=coef(nzm_glm_het_adv), confint(nzm_glm_het_adv))), Pvalue=summary(nzm_glm_het_adv)$coefficients[,4]),3))
het_adv_table(round(cbind(exp(cbind(OR=coef(cim_glm_het_adv), confint(cim_glm_het_adv))), Pvalue=summary(cim_glm_het_adv)$coefficients[,4]),3))
het_adv_table(round(cbind(exp(cbind(OR=coef(samoan_glm_het_adv), confint(samoan_glm_het_adv))), Pvalue=summary(samoan_glm_het_adv)$coefficients[,4]),3))
het_adv_table(round(cbind(exp(cbind(OR=coef(tongan_glm_het_adv), confint(tongan_glm_het_adv))), Pvalue=summary(tongan_glm_het_adv)$coefficients[,4]),3))
het_adv_table(round(cbind(exp(cbind(OR=coef(combined_poly_glm_het_adv), confint(combined_poly_glm_het_adv))), Pvalue=summary(combined_poly_glm_het_adv)$coefficients[,4]),3))
het_adv_table(round(cbind(exp(cbind(OR=coef(combined_all_glm_het_adv), confint(combined_all_glm_het_adv))), Pvalue=summary(combined_all_glm_het_adv)$coefficients[,4]),3))



basic_info=function(x){
  print("BMI")
  print(summary(x$BMI))
  print("AGECOL")
  print(summary(x$AGECOL))
  print("SEX")
  print(table(x$SEX.x,exclude=NULL))
  print("DIABETES")
  print(table(x$DIABETES,exclude=NULL))
  print("STANCESTRY")
  print(summary(x$STANCESTRY))
  print("RS8192678_CC1_CT2_TT3")
  print(table(x$RS8192678_CC1_CT2_TT3,exclude=NULL))
  print("FULLCAUGTAFF")
  print(table(x$FULLCAUGTAFF, exclude=NULL))
  print("FULLEPGTAFF")
  print(table(x$FULLEPGTAFF, exclude=NULL))
  print("FULLWPGTAFF")
  print(table(x$FULLWPGTAFF, exclude=NULL))
  print("FULLEPWPGTAFF")
  print(table(x$FULLEPWPGTAFF, exclude=NULL))
}
