# Murray Cadzow
# Aug 2013

#merged_haploped_pheno_gt=read.csv("~/Documents/PPARGC1A/merged_haploped_pheno_gt.txt", header=TRUE, sep="\t")
merged_haploped_pheno_gt=read.csv("~/Documents/PPARGC1A/Analysis/pheno_gt_ato_g.csv", header=TRUE, sep="\t")
merged_haploped_pheno_gt$DOM_c =ifelse( merged_haploped_pheno_gt$RS8192678_CC1_CT2_TT3 ==1 | merged_haploped_pheno_gt$RS8192678_CC1_CT2_TT3 ==2 , 1, 0)
merged_haploped_pheno_gt$DOM_t =ifelse( merged_haploped_pheno_gt$RS8192678_CC1_CT2_TT3 ==3 | merged_haploped_pheno_gt$RS8192678_CC1_CT2_TT3 ==2 , 1, 0)
merged_haploped_pheno_gt$het_adv =ifelse( merged_haploped_pheno_gt$RS8192678_CC1_CT2_TT3 ==2 , 1, 0)

cases=subset(merged_haploped_pheno_gt, merged_haploped_pheno_gt$GOUTAFFSTAT==2)
controls=subset(merged_haploped_pheno_gt, merged_haploped_pheno_gt$GOUTAFFSTAT==1)
nzm=subset(merged_haploped_pheno_gt, merged_haploped_pheno_gt$ETHNICITY=="1.0 NZ Maori")
nzm_c=subset(nzm, nzm$FULLEPGTAFF==1)
nzm_g=subset(nzm, nzm$FULLEPGTAFF==2)

samoan=subset(merged_haploped_pheno_gt, merged_haploped_pheno_gt$ETHNICITY=="1.0 Samoan")
samoan_g=subset(samoan, samoan$FULLWPGTAFF==2)
samoan_c=subset(samoan, samoan$FULLWPGTAFF==1)

tongan=subset(merged_haploped_pheno_gt, merged_haploped_pheno_gt$ETHNICITY=="1.0 Tongan")
tongan_c=subset(tongan,tongan$FULLWPGTAFF==1)
tongan_g=subset(tongan, tongan$FULLWPGTAFF==2)

cim=subset(merged_haploped_pheno_gt, merged_haploped_pheno_gt$ETHNICITY=="1.0 CI Maori")
cim_c=subset(cim, cim$FULLEPGTAFF==1)
cim_g=subset(cim, cim$FULLEPGTAFF==2)

merged_haploped_pheno_gt$ETHNICITY[merged_haploped_pheno_gt$ETHNICITY == "1.0 Caucasain"] = "1.0 Caucasian"

##CAU groups
CAU=subset(merged_haploped_pheno_gt, merged_haploped_pheno_gt$FULLCAUGTAFF==1 | merged_haploped_pheno_gt$FULLCAUGTAFF==2)
CAU_g=subset(CAU, CAU$FULLCAUGTAFF==2)
CAU_c=subset(CAU, CAU$FULLCAUGTAFF==1)

## EP groups
EP=subset(merged_haploped_pheno_gt, merged_haploped_pheno_gt$FULLEPGTAFF==1 | merged_haploped_pheno_gt$FULLEPGTAFF==2)

EPN=subset(EP, EP$EPNEPZ==1)
EPN_c=subset(EPN, EPN$FULLEPGTAFF==1)
EPN_g=subset(EPN, EPN$FULLEPGTAFF==2)

EPZ=subset(EP,EP$EPNEPZ==2)
EPZ_c=subset(EPZ, EPZ$FULLEPGTAFF==1)
EPZ_g=subset(EPZ, EPZ$FULLEPGTAFF==2)

EPWP=subset(merged_haploped_pheno_gt, merged_haploped_pheno_gt$FULLEPWPGTAFF==1 | merged_haploped_pheno_gt$FULLEPWPGTAFF==2)
EPWP_c=subset(EPWP, EPWP$FULLEPWPGTAFF==1)
EPWP_g=subset(EPWP, EPWP$FULLEPWPGTAFF==2)

## WP groups
WP=subset(merged_haploped_pheno_gt, merged_haploped_pheno_gt$FULLWPGTAFF==1 | merged_haploped_pheno_gt$FULLWPGTAFF==2)
WP_c=subset(WP, WP$FULLWPGTAFF==1)
WP_g=subset(WP, WP$FULLWPGTAFF==2)


CAU_mod=CAU
CAU_mod$STANCESTRY=rep(0, length(CAU_mod[,1]))
CAU_mod=CAU_mod[c("FULLCAUGTAFF", "DIABETES", "STANCESTRY", "SEX.x","AGECOL", "BMI", "RS8192678_CC1_CT2_TT3", "DOM_c","DOM_t", "het_adv")]
colnames(CAU_mod) = c("FULLGTAFF", "DIABETES", "STANCESTRY", "SEX.x","AGECOL", "BMI", "RS8192678_CC1_CT2_TT3", "DOM_c","DOM_t", "het_adv")
CAU_mod$POP=rep("CAU", length(CAU_mod[,1]))

EPN_mod=EPN[c("FULLEPGTAFF", "DIABETES", "STANCESTRY", "SEX.x","AGECOL", "BMI", "RS8192678_CC1_CT2_TT3", "DOM_c","DOM_t", "het_adv")]
colnames(EPN_mod) = c("FULLGTAFF", "DIABETES", "STANCESTRY", "SEX.x","AGECOL", "BMI", "RS8192678_CC1_CT2_TT3", "DOM_c","DOM_t", "het_adv")
EPN_mod$POP = rep("EPN", length(EPN_mod[,1]))

EPZ_mod=EPZ[c("FULLEPGTAFF", "DIABETES", "STANCESTRY", "SEX.x","AGECOL", "BMI", "RS8192678_CC1_CT2_TT3", "DOM_c","DOM_t", "het_adv")]
colnames(EPZ_mod) = c("FULLGTAFF", "DIABETES", "STANCESTRY", "SEX.x","AGECOL", "BMI", "RS8192678_CC1_CT2_TT3", "DOM_c","DOM_t", "het_adv")
EPZ_mod$POP = rep("EPZ", length(EPZ_mod[,1]))

WP_mod=WP[c("FULLWPGTAFF", "DIABETES", "STANCESTRY", "SEX.x","AGECOL", "BMI", "RS8192678_CC1_CT2_TT3", "DOM_c","DOM_t", "het_adv")]
colnames(WP_mod) = c("FULLGTAFF", "DIABETES", "STANCESTRY", "SEX.x","AGECOL", "BMI", "RS8192678_CC1_CT2_TT3", "DOM_c","DOM_t", "het_adv")
WP_mod$POP = rep("WP", length(WP_mod[,1]))

EPWP_mod= EPWP[c("FULLEPWPGTAFF", "DIABETES", "STANCESTRY", "SEX.x","AGECOL", "BMI", "RS8192678_CC1_CT2_TT3", "DOM_c","DOM_t", "het_adv")]
colnames(EPWP_mod) = c("FULLGTAFF", "DIABETES", "STANCESTRY", "SEX.x","AGECOL", "BMI", "RS8192678_CC1_CT2_TT3", "DOM_c","DOM_t", "het_adv")
EPWP_mod$POP = rep("EPWP", length(EPWP_mod[,1]))




combined_all = rbind(CAU_mod, EPN_mod, EPZ_mod, WP_mod, EPWP_mod)
combined_poly = rbind(EPN_mod, EPZ_mod, WP_mod, EPWP_mod)


combined_poly_lm_additive = lm(combined_poly$BMI ~ as.factor(combined_poly$FULLGTAFF) + as.factor(combined_poly$DIABETES) + combined_poly$STANCESTRY +  as.factor(combined_poly$SEX.x) + combined_poly$AGECOL + as.factor(combined_poly$POP) * combined_poly$RS8192678_CC1_CT2_TT3)
combined_poly_lm_domc = lm(combined_poly$BMI ~ as.factor(combined_poly$FULLGTAFF) + as.factor(combined_poly$DIABETES) + combined_poly$STANCESTRY +  as.factor(combined_poly$SEX.x) + combined_poly$AGECOL + as.factor(combined_poly$POP) * combined_poly$DOM_c)
combined_poly_lm_domt = lm(combined_poly$BMI ~ as.factor(combined_poly$FULLGTAFF) + as.factor(combined_poly$DIABETES) + combined_poly$STANCESTRY +  as.factor(combined_poly$SEX.x) + combined_poly$AGECOL + as.factor(combined_poly$POP) * combined_poly$DOM_t)
combined_poly_lm_het_adv = lm(combined_poly$BMI ~ as.factor(combined_poly$FULLGTAFF) + as.factor(combined_poly$DIABETES) + combined_poly$STANCESTRY +  as.factor(combined_poly$SEX.x) + combined_poly$AGECOL + as.factor(combined_poly$POP) * combined_poly$het_adv)

summary(combined_poly_lm_additive)
summary(combined_poly_lm_domc)
summary(combined_poly_lm_domt)
summary(combined_poly_lm_het_adv)


combined_all_lm_additive = lm(combined_all$BMI ~ as.factor(combined_all$FULLGTAFF) + as.factor(combined_all$DIABETES) + combined_all$STANCESTRY +  as.factor(combined_all$SEX.x) + combined_all$AGECOL + as.factor(combined_all$POP) * combined_all$RS8192678_CC1_CT2_TT3)
combined_all_lm_domc = lm(combined_all$BMI ~ as.factor(combined_all$FULLGTAFF) + as.factor(combined_all$DIABETES) + combined_all$STANCESTRY +  as.factor(combined_all$SEX.x) + combined_all$AGECOL + as.factor(combined_all$POP) * combined_all$DOM_c)
combined_all_lm_domt = lm(combined_all$BMI ~ as.factor(combined_all$FULLGTAFF) + as.factor(combined_all$DIABETES) + combined_all$STANCESTRY +  as.factor(combined_all$SEX.x) + combined_all$AGECOL + as.factor(combined_all$POP) * combined_all$DOM_t)
combined_all_lm_het_adv = lm(combined_all$BMI ~ as.factor(combined_all$FULLGTAFF) + as.factor(combined_all$DIABETES) + combined_all$STANCESTRY +  as.factor(combined_all$SEX.x) + combined_all$AGECOL + as.factor(combined_all$POP) * combined_all$het_adv)

summary(combined_all_lm_additive)
summary(combined_all_lm_domc)
summary(combined_all_lm_domt)
summary(combined_all_lm_het_adv)


#################################################
## regressions ADDITIVE MODEL ##################
##############################################
cau_lm_additive=lm(CAU$BMI ~ as.factor(CAU$FULLCAUGTAFF) + CAU$AGECOL + as.factor(CAU$SEX.x) + as.factor(CAU$DIABETES)  + CAU$RS8192678_CC1_CT2_TT3)
cau_g_lm_additive=lm(CAU_g$BMI ~ CAU_g$AGECOL + as.factor(CAU_g$SEX.x) + as.factor(CAU_g$DIABETES)  + CAU_g$RS8192678_CC1_CT2_TT3)
cau_c_lm_additive=lm(CAU_c$BMI ~ CAU_c$AGECOL + as.factor(CAU_c$SEX.x) + as.factor(CAU_c$DIABETES)  + CAU_c$RS8192678_CC1_CT2_TT3)

wp_lm_additive=lm(WP$BMI ~ as.factor(WP$FULLWPGTAFF) + WP$AGECOL + as.factor(WP$SEX.x) + as.factor(WP$DIABETES) +WP$STANCESTRY+ WP$RS8192678_CC1_CT2_TT3)
wp_g_lm_additive=lm(WP_g$BMI ~ WP_g$AGECOL + as.factor(WP_g$SEX.x) + as.factor(WP_g$DIABETES) +WP_g$STANCESTRY+ WP_g$RS8192678_CC1_CT2_TT3)
wp_c_lm_additive=lm(WP_c$BMI ~ WP_c$AGECOL + as.factor(WP_c$SEX.x) + as.factor(WP_c$DIABETES) +WP_c$STANCESTRY+ WP_c$RS8192678_CC1_CT2_TT3)

epn_lm_additive=lm(EPN$BMI ~ as.factor(EPN$FULLEPGTAFF) + EPN$AGECOL + as.factor(EPN$SEX.x) + as.factor(EPN$DIABETES) +EPN$STANCESTRY + EPN$RS8192678_CC1_CT2_TT3)
epn_g_lm_additive=lm(EPN_g$BMI ~ EPN_g$AGECOL + as.factor(EPN_g$SEX.x) + as.factor(EPN_g$DIABETES) +EPN_g$STANCESTRY + EPN_g$RS8192678_CC1_CT2_TT3)
epn_c_lm_additive=lm(EPN_c$BMI ~ EPN_c$AGECOL + as.factor(EPN_c$SEX.x) + as.factor(EPN_c$DIABETES) +EPN_c$STANCESTRY + EPN_c$RS8192678_CC1_CT2_TT3)

epz_lm_additive=lm(EPZ$BMI ~ as.factor(EPZ$FULLEPGTAFF) + EPZ$AGECOL + as.factor(EPZ$SEX.x) + as.factor(EPZ$DIABETES) +EPZ$STANCESTRY + EPZ$RS8192678_CC1_CT2_TT3)
epz_g_lm_additive=lm(EPZ_g$BMI ~ EPZ_g$AGECOL + as.factor(EPZ_g$SEX.x) + as.factor(EPZ_g$DIABETES) +EPZ_g$STANCESTRY + EPZ_g$RS8192678_CC1_CT2_TT3)
epz_c_lm_additive=lm(EPZ_c$BMI ~ EPZ_c$AGECOL + as.factor(EPZ_c$SEX.x) + as.factor(EPZ_c$DIABETES) +EPZ_c$STANCESTRY + EPZ_c$RS8192678_CC1_CT2_TT3)

epwp_lm_additive=lm(EPWP$BMI ~ as.factor(EPWP$FULLEPWPGTAFF) + EPWP$AGECOL + as.factor(EPWP$SEX.x) + as.factor(EPWP$DIABETES) +EPWP$STANCESTRY + EPWP$RS8192678_CC1_CT2_TT3)
epwp_g_lm_additive=lm(EPWP_g$BMI ~ EPWP_g$AGECOL + as.factor(EPWP_g$SEX.x) + as.factor(EPWP_g$DIABETES) +EPWP_g$STANCESTRY + EPWP_g$RS8192678_CC1_CT2_TT3)
epwp_c_lm_additive=lm(EPWP_c$BMI ~ EPWP_c$AGECOL + as.factor(EPWP_c$SEX.x) + as.factor(EPWP_c$DIABETES) +EPWP_c$STANCESTRY + EPWP_c$RS8192678_CC1_CT2_TT3)


nzm_lm_additive=lm(nzm$BMI ~ as.factor(nzm$FULLEPGTAFF) + nzm$AGECOL + as.factor(nzm$SEX.x) + as.factor(nzm$DIABETES) +nzm$STANCESTRY+ nzm$RS8192678_CC1_CT2_TT3)
nzm_g_lm_additive=lm(nzm_g$BMI ~ nzm_g$AGECOL + as.factor(nzm_g$SEX.x) + as.factor(nzm_g$DIABETES) +nzm_g$STANCESTRY+ nzm_g$RS8192678_CC1_CT2_TT3)
nzm_c_lm_additive=lm(nzm_c$BMI ~ nzm_c$AGECOL + as.factor(nzm_c$SEX.x) + as.factor(nzm_c$DIABETES) +nzm_c$STANCESTRY+ nzm_c$RS8192678_CC1_CT2_TT3)

cim_lm_additive=lm(cim$BMI ~ as.factor(cim$FULLEPGTAFF) + cim$AGECOL + as.factor(cim$SEX.x) + as.factor(cim$DIABETES) +cim$STANCESTRY+ cim$RS8192678_CC1_CT2_TT3)
cim_g_lm_additive=lm(cim_g$BMI ~ cim_g$AGECOL + as.factor(cim_g$SEX.x) + as.factor(cim_g$DIABETES) +cim_g$STANCESTRY+ cim_g$RS8192678_CC1_CT2_TT3)
cim_c_lm_additive=lm(cim_c$BMI ~ cim_c$AGECOL + as.factor(cim_c$SEX.x) + as.factor(cim_c$DIABETES) +cim_c$STANCESTRY+ cim_c$RS8192678_CC1_CT2_TT3)

samoan_lm_additive=lm(samoan$BMI ~ as.factor(samoan$FULLWPGTAFF) + samoan$AGECOL + as.factor(samoan$SEX.x) + as.factor(samoan$DIABETES) +samoan$STANCESTRY+ samoan$RS8192678_CC1_CT2_TT3)
samoan_g_lm_additive=lm(samoan_g$BMI ~ samoan_g$AGECOL + as.factor(samoan_g$SEX.x) + as.factor(samoan_g$DIABETES) +samoan_g$STANCESTRY+ samoan_g$RS8192678_CC1_CT2_TT3)
samoan_c_lm_additive=lm(samoan_c$BMI ~ samoan_c$AGECOL + as.factor(samoan_c$SEX.x) + as.factor(samoan_c$DIABETES) +samoan_c$STANCESTRY+ samoan_c$RS8192678_CC1_CT2_TT3)

tongan_lm_additive=lm(tongan$BMI ~ as.factor(tongan$FULLWPGTAFF) + tongan$AGECOL + as.factor(tongan$SEX.x) + as.factor(tongan$DIABETES) +tongan$STANCESTRY+ tongan$RS8192678_CC1_CT2_TT3)
tongan_g_lm_additive=lm(tongan_g$BMI ~ tongan_g$AGECOL + as.factor(tongan_g$SEX.x) + as.factor(tongan_g$DIABETES) +tongan_g$STANCESTRY+ tongan_g$RS8192678_CC1_CT2_TT3)
tongan_c_lm_additive=lm(tongan_c$BMI ~ tongan_c$AGECOL + as.factor(tongan_c$SEX.x) + as.factor(tongan_c$DIABETES) +tongan_c$STANCESTRY+ tongan_c$RS8192678_CC1_CT2_TT3)

sink(file="additive_model.txt")
# summary(cau_lm_additive)
# #summary(cau_c_lm_additive)
# #summary(cau_g_lm_additive)
# #summary(epn_lm_additive)
# #summary(epn_c_lm_additive)
# #summary(epn_g_lm_additive)
# #summary(epz_lm_additive)
# #summary(epz_c_lm_additive)
# #summary(epz_g_lm_additive)
# #summary(wp_lm_additive)
# #summary(wp_c_lm_additive)
# #summary(wp_g_lm_additive)
# #summary(epwp_lm_additive)
# #summary(epwp_c_lm_additive)
# #summary(epwp_g_lm_additive)
# summary(nzm_lm_additive)
# #summary(nzm_c_lm_additive)
# #summary(nzm_g_lm_additive)
# summary(cim_lm_additive)
# #summary(cim_c_lm_additive)
# #summary(cim_g_lm_additive)
# summary(samoan_lm_additive)
# #summary(samoan_c_lm_additive)
# #summary(samoan_g_lm_additive)
# summary(tongan_lm_additive)
# #summary(tongan_c_lm_additive)
# #summary(tongan_g_lm_additive)
# #summary(combined_poly_lm_additive)
# #summary(combined_all_lm_additive)
# confint(cau_lm_additive)
# #confint(cau_c_lm_additive)
# #confint(cau_g_lm_additive)
# #confint(epn_lm_additive)
# #confint(epn_c_lm_additive)
# #confint(epn_g_lm_additive)
# #confint(epz_lm_additive)
# #confint(epz_c_lm_additive)
# #confint(epz_g_lm_additive)
# #confint(wp_lm_additive)
# #confint(wp_c_lm_additive)
# #confint(wp_g_lm_additive)
# #confint(epwp_lm_additive)
# #confint(epwp_c_lm_additive)
# #confint(epwp_g_lm_additive)
# confint(nzm_lm_additive)
# #confint(nzm_c_lm_additive)
# #confint(nzm_g_lm_additive)
# confint(cim_lm_additive)
# #confint(cim_c_lm_additive)
# #confint(cim_g_lm_additive)
# confint(samoan_lm_additive)
# #confint(samoan_c_lm_additive)
# #confint(samoan_g_lm_additive)
# confint(tongan_lm_additive)
# #confint(tongan_c_lm_additive)
# #confint(tongan_g_lm_additive)
# #confint(combined_poly_lm_additive)
# #confint(combined_all_lm_additive)

round(cbind((cbind(beta= coef(cau_lm_additive), confint(cau_lm_additive))),Pvalue= summary(cau_lm_additive)$coefficients[,4]),3)
round(cbind((cbind(beta=coef(nzm_lm_additive), confint(nzm_lm_additive))), Pvalue=summary(nzm_lm_additive)$coefficients[,4]), 3)
round(cbind((cbind(beta=coef(cim_lm_additive), confint(cim_lm_additive))), Pvalue=summary(cim_lm_additive)$coefficients[,4]), 3)
round(cbind((cbind(beta=coef(samoan_lm_additive), confint(samoan_lm_additive))), Pvalue=summary(samoan_lm_additive)$coefficients[,4]),3)
round(cbind((cbind(beta=coef(tongan_lm_additive), confint(tongan_lm_additive))), Pvalue=summary(tongan_lm_additive)$coefficients[,4]),3)
round(cbind((cbind(beta=coef(combined_poly_lm_additive), confint(combined_poly_lm_additive))), Pvalue=summary(combined_poly_lm_additive)$coefficients[,4]),3)
round(cbind((cbind(beta=coef(combined_all_lm_additive), confint(combined_all_lm_additive))), Pvalue=summary(combined_all_lm_additive)$coefficients[,4]),3)

sink()

additive_table=function(x){write.table(x, file="additive_table.csv",sep="\t", quote=FALSE, append=TRUE)}
# additive_table(summary(cau_lm_additive)$coefficients)
#additive_table(summary(cau_c_lm_additive)$coefficients)
#additive_table(summary(cau_g_lm_additive)$coefficients)
#additive_table(summary(epn_lm_additive)$coefficients)
#additive_table(summary(epn_c_lm_additive)$coefficients)
#additive_table(summary(epn_g_lm_additive)$coefficients)
#additive_table(summary(epz_lm_additive)$coefficients)
#additive_table(summary(epz_c_lm_additive)$coefficients)
#additive_table(summary(epz_g_lm_additive)$coefficients)
#additive_table(summary(wp_lm_additive)$coefficients)
#additive_table(summary(wp_c_lm_additive)$coefficients)
#additive_table(summary(wp_g_lm_additive)$coefficients)
#additive_table(summary(epwp_lm_additive)$coefficients)
# additive_table(summary(epwp_c_lm_additive)$coefficients)
# additive_table(summary(epwp_g_lm_additive)$coefficients)
# additive_table(summary(nzm_lm_additive)$coefficients)
# # additive_table(summary(nzm_c_lm_additive)$coefficients)
# # additive_table(summary(nzm_g_lm_additive)$coefficients)
# additive_table(summary(cim_lm_additive)$coefficients)
# # additive_table(summary(cim_c_lm_additive)$coefficients)
# # additive_table(summary(cim_g_lm_additive)$coefficients)
# additive_table(summary(samoan_lm_additive)$coefficients)
# # additive_table(summary(samoan_c_lm_additive)$coefficients)
# # additive_table(summary(samoan_g_lm_additive)$coefficients)
# additive_table(summary(tongan_lm_additive)$coefficients)
# # additive_table(summary(tongan_c_lm_additive)$coefficients)
# # additive_table(summary(tongan_g_lm_additive)$coefficients)
# # additive_table(summary(combined_poly_lm_additive)$coefficients)
# # additive_table(summary(combined_all_lm_additive)$coefficients)
# additive_table(confint(cau_lm_additive))
# # additive_table(confint(cau_c_lm_additive))
# # additive_table(confint(cau_g_lm_additive))
# # additive_table(confint(epn_lm_additive))
# # additive_table(confint(epn_c_lm_additive))
# # additive_table(confint(epn_g_lm_additive))
# # additive_table(confint(epz_lm_additive))
# # additive_table(confint(epz_c_lm_additive))
# # additive_table(confint(epz_g_lm_additive))
# # additive_table(confint(wp_lm_additive))
# # additive_table(confint(wp_c_lm_additive))
# # additive_table(confint(wp_g_lm_additive))
# # additive_table(confint(epwp_lm_additive))
# # additive_table(confint(epwp_c_lm_additive))
# # additive_table(confint(epwp_g_lm_additive))
# additive_table(confint(nzm_lm_additive))
# # additive_table(confint(nzm_c_lm_additive))
# # additive_table(confint(nzm_g_lm_additive))
# additive_table(confint(cim_lm_additive))
# # additive_table(confint(cim_c_lm_additive))
# # additive_table(confint(cim_g_lm_additive))
# additive_table(confint(samoan_lm_additive))
# # additive_table(confint(samoan_c_lm_additive))
# # additive_table(confint(samoan_g_lm_additive))
# additive_table(confint(tongan_lm_additive))
# # additive_table(confint(tongan_c_lm_additive))
# # additive_table(confint(tongan_g_lm_additive))
# # additive_table(confint(combined_poly_lm_additive))
# # additive_table(confint(combined_all_lm_additive))
additive_table(round(cbind((cbind(beta= coef(cau_lm_additive), confint(cau_lm_additive))),Pvalue= summary(cau_lm_additive)$coefficients[,4]),3))
additive_table(round(cbind((cbind(beta=coef(nzm_lm_additive), confint(nzm_lm_additive))), Pvalue=summary(nzm_lm_additive)$coefficients[,4]),3))
additive_table(round(cbind((cbind(beta=coef(cim_lm_additive), confint(cim_lm_additive))), Pvalue=summary(cim_lm_additive)$coefficients[,4]),3))
additive_table(round(cbind((cbind(beta=coef(samoan_lm_additive), confint(samoan_lm_additive))), Pvalue=summary(samoan_lm_additive)$coefficients[,4]),3))
additive_table(round(cbind((cbind(beta=coef(tongan_lm_additive), confint(tongan_lm_additive))), Pvalue=summary(tongan_lm_additive)$coefficients[,4]),3))
additive_table(round(cbind((cbind(beta=coef(combined_poly_lm_additive), confint(combined_poly_lm_additive))), Pvalue=summary(combined_poly_lm_additive)$coefficients[,4]),3))
additive_table(round(cbind((cbind(beta=coef(combined_all_lm_additive), confint(combined_all_lm_additive))), Pvalue=summary(combined_all_lm_additive)$coefficients[,4]),3))



# write.table(x=confint(cau_lm_additive, level=0.95), file="additive_CI.csv", sep="\t",quote=FALSE, append=TRUE)
# write.table(x=confint(cau_c_lm_additive, level=0.95),file="additive_CI.csv", sep="\t",quote=FALSE, append=TRUE)
# write.table(x=confint(cau_g_lm_additive, level=0.95),file="additive_CI.csv", sep="\t",quote=FALSE, append=TRUE)
# write.table(x=confint(epn_lm_additive, level=0.95),file="additive_CI.csv", sep="\t",quote=FALSE, append=TRUE)
# write.table(x=confint(epn_c_lm_additive, level=0.95),file="additive_CI.csv", sep="\t",quote=FALSE, append=TRUE)
# write.table(x=confint(epn_g_lm_additive, level=0.95),file="additive_CI.csv", sep="\t",quote=FALSE, append=TRUE)
# write.table(x=confint(epz_lm_additive, level=0.95),file="additive_CI.csv", sep="\t",quote=FALSE, append=TRUE)
# write.table(x=confint(epz_c_lm_additive, level=0.95),file="additive_CI.csv", sep="\t",quote=FALSE, append=TRUE)
# write.table(x=confint(epz_g_lm_additive, level=0.95),file="additive_CI.csv", sep="\t",quote=FALSE, append=TRUE)
# write.table(x=confint(wp_lm_additive, level=0.95),file="additive_CI.csv", sep="\t",quote=FALSE, append=TRUE)
# write.table(x=confint(wp_c_lm_additive, level=0.95),file="additive_CI.csv", sep="\t",quote=FALSE, append=TRUE)
# write.table(x=confint(wp_g_lm_additive, level=0.95),file="additive_CI.csv", sep="\t",quote=FALSE, append=TRUE)
# write.table(x=confint(epwp_lm_additive, level=0.95),file="additive_CI.csv", sep="\t",quote=FALSE, append=TRUE)
# write.table(x=confint(epwp_c_lm_additive, level=0.95),file="additive_CI.csv", sep="\t",quote=FALSE, append=TRUE)
# write.table(x=confint(epwp_g_lm_additive, level=0.95),file="additive_CI.csv", sep="\t",quote=FALSE, append=TRUE)
# write.table(x=confint(nzm_lm_additive, level=0.95),file="additive_CI.csv", sep="\t",quote=FALSE, append=TRUE)
# # write.table(x=confint(nzm_c_lm_additive, level=0.95),file="additive_CI.csv", sep="\t",quote=FALSE, append=TRUE)
# # write.table(x=confint(nzm_g_lm_additive, level=0.95),file="additive_CI.csv", sep="\t",quote=FALSE, append=TRUE)
# write.table(x=confint(cim_lm_additive, level=0.95),file="additive_CI.csv", sep="\t",quote=FALSE, append=TRUE)
# # write.table(x=confint(cim_c_lm_additive, level=0.95),file="additive_CI.csv", sep="\t",quote=FALSE, append=TRUE)
# # write.table(x=confint(cim_g_lm_additive, level=0.95),file="additive_CI.csv", sep="\t",quote=FALSE, append=TRUE)
# write.table(x=confint(samoan_lm_additive, level=0.95),file="additive_CI.csv", sep="\t",quote=FALSE, append=TRUE)
# # write.table(x=confint(samoan_c_lm_additive, level=0.95),file="additive_CI.csv", sep="\t",quote=FALSE, append=TRUE)
# # write.table(x=confint(samoan_g_lm_additive, level=0.95),file="additive_CI.csv", sep="\t",quote=FALSE, append=TRUE)
# write.table(x=confint(tongan_lm_additive, level=0.95),file="additive_CI.csv", sep="\t",quote=FALSE, append=TRUE)
# write.table(x=confint(tongan_c_lm_additive, level=0.95),file="additive_CI.csv", sep="\t",quote=FALSE, append=TRUE)
# write.table(x=confint(tongan_g_lm_additive, level=0.95),file="additive_CI.csv", sep="\t",quote=FALSE, append=TRUE)



#################################################
## regressions DOMINANT CC MODEL ###############
##############################################
cau_lm_domc=lm(CAU$BMI ~ as.factor(CAU$FULLCAUGTAFF) + CAU$AGECOL + as.factor(CAU$SEX.x) + as.factor(CAU$DIABETES)  + as.factor(CAU$DOM_c))
cau_g_lm_domc=lm(CAU_g$BMI ~ CAU_g$AGECOL + as.factor(CAU_g$SEX.x) + as.factor(CAU_g$DIABETES)  + as.factor(CAU_g$DOM_c))
cau_c_lm_domc=lm(CAU_c$BMI ~ CAU_c$AGECOL + as.factor(CAU_c$SEX.x) + as.factor(CAU_c$DIABETES)  + as.factor(CAU_c$DOM_c))

wp_lm_domc=lm(WP$BMI ~ as.factor(WP$FULLWPGTAFF) + WP$AGECOL + as.factor(WP$SEX.x) + as.factor(WP$DIABETES) +WP$STANCESTRY+ as.factor(WP$DOM_c))
wp_g_lm_domc=lm(WP_g$BMI ~ WP_g$AGECOL + as.factor(WP_g$SEX.x) + as.factor(WP_g$DIABETES) +WP_g$STANCESTRY+ as.factor(WP_g$DOM_c))
wp_c_lm_domc=lm(WP_c$BMI ~ WP_c$AGECOL + as.factor(WP_c$SEX.x) + as.factor(WP_c$DIABETES) +WP_c$STANCESTRY+ as.factor(WP_c$DOM_c))

epn_lm_domc=lm(EPN$BMI ~ as.factor(EPN$FULLEPGTAFF) + EPN$AGECOL + as.factor(EPN$SEX.x) + as.factor(EPN$DIABETES) +EPN$STANCESTRY + as.factor(EPN$DOM_c))
epn_g_lm_domc=lm(EPN_g$BMI ~ EPN_g$AGECOL + as.factor(EPN_g$SEX.x) + as.factor(EPN_g$DIABETES) +EPN_g$STANCESTRY +as.factor(EPN_g$DOM_c))
epn_c_lm_domc=lm(EPN_c$BMI ~ EPN_c$AGECOL + as.factor(EPN_c$SEX.x) + as.factor(EPN_c$DIABETES) +EPN_c$STANCESTRY + as.factor(EPN_c$DOM_c))

epz_lm_domc=lm(EPZ$BMI ~ as.factor(EPZ$FULLEPGTAFF) + EPZ$AGECOL + as.factor(EPZ$SEX.x) + as.factor(EPZ$DIABETES) +EPZ$STANCESTRY + as.factor(EPZ$DOM_c))
epz_g_lm_domc=lm(EPZ_g$BMI ~ EPZ_g$AGECOL + as.factor(EPZ_g$SEX.x) + as.factor(EPZ_g$DIABETES) +EPZ_g$STANCESTRY + as.factor(EPZ_g$DOM_c))
epz_c_lm_domc=lm(EPZ_c$BMI ~ EPZ_c$AGECOL + as.factor(EPZ_c$SEX.x) + as.factor(EPZ_c$DIABETES) +EPZ_c$STANCESTRY + as.factor(EPZ_c$DOM_c))

epwp_lm_domc=lm(EPWP$BMI ~ as.factor(EPWP$FULLEPWPGTAFF) + EPWP$AGECOL + as.factor(EPWP$SEX.x) + as.factor(EPWP$DIABETES) +EPWP$STANCESTRY + as.factor(EPWP$DOM_c))
epwp_g_lm_domc=lm(EPWP_g$BMI ~ EPWP_g$AGECOL + as.factor(EPWP_g$SEX.x) + as.factor(EPWP_g$DIABETES) +EPWP_g$STANCESTRY + as.factor(EPWP_g$DOM_c))
epwp_c_lm_domc=lm(EPWP_c$BMI ~ EPWP_c$AGECOL + as.factor(EPWP_c$SEX.x) + as.factor(EPWP_c$DIABETES) +EPWP_c$STANCESTRY + as.factor(EPWP_c$DOM_c))

nzm_lm_domc=lm(nzm$BMI ~ as.factor(nzm$FULLEPGTAFF) + nzm$AGECOL + as.factor(nzm$SEX.x) + as.factor(nzm$DIABETES) +nzm$STANCESTRY+ as.factor(nzm$DOM_c))
nzm_g_lm_domc=lm(nzm_g$BMI ~ nzm_g$AGECOL + as.factor(nzm_g$SEX.x) + as.factor(nzm_g$DIABETES) +nzm_g$STANCESTRY+ as.factor(nzm_g$DOM_c))
nzm_c_lm_domc=lm(nzm_c$BMI ~ nzm_c$AGECOL + as.factor(nzm_c$SEX.x) + as.factor(nzm_c$DIABETES) +nzm_c$STANCESTRY+ as.factor(nzm_c$DOM_c))

cim_lm_domc=lm(cim$BMI ~ as.factor(cim$FULLEPGTAFF) + cim$AGECOL + as.factor(cim$SEX.x) + as.factor(cim$DIABETES) +cim$STANCESTRY+ as.factor(cim$DOM_c))
cim_g_lm_domc=lm(cim_g$BMI ~ cim_g$AGECOL + as.factor(cim_g$SEX.x) + as.factor(cim_g$DIABETES) +cim_g$STANCESTRY+ as.factor(cim_g$DOM_c))
cim_c_lm_domc=lm(cim_c$BMI ~ cim_c$AGECOL + as.factor(cim_c$SEX.x) + as.factor(cim_c$DIABETES) +cim_c$STANCESTRY+ as.factor(cim_c$DOM_c))

samoan_lm_domc=lm(samoan$BMI ~ as.factor(samoan$FULLWPGTAFF) + samoan$AGECOL + as.factor(samoan$SEX.x) + as.factor(samoan$DIABETES) +samoan$STANCESTRY+ as.factor(samoan$DOM_c))
samoan_g_lm_domc=lm(samoan_g$BMI ~ samoan_g$AGECOL + as.factor(samoan_g$SEX.x) + as.factor(samoan_g$DIABETES) +samoan_g$STANCESTRY+ as.factor(samoan_g$DOM_c))
samoan_c_lm_domc=lm(samoan_c$BMI ~ samoan_c$AGECOL + as.factor(samoan_c$SEX.x) + as.factor(samoan_c$DIABETES) +samoan_c$STANCESTRY+ as.factor(samoan_c$DOM_c))

tongan_lm_domc=lm(tongan$BMI ~ as.factor(tongan$FULLWPGTAFF) + tongan$AGECOL + as.factor(tongan$SEX.x) + as.factor(tongan$DIABETES) +tongan$STANCESTRY+ as.factor(tongan$DOM_c))
tongan_g_lm_domc=lm(tongan_g$BMI ~ tongan_g$AGECOL + as.factor(tongan_g$SEX.x) + as.factor(tongan_g$DIABETES) +tongan_g$STANCESTRY+ as.factor(tongan_g$DOM_c))
tongan_c_lm_domc=lm(tongan_c$BMI ~ tongan_c$AGECOL + as.factor(tongan_c$SEX.x) + as.factor(tongan_c$DIABETES) +tongan_c$STANCESTRY+ as.factor(tongan_c$DOM_c))

sink(file="dominant_CC_model.txt")
# summary(cau_lm_domc)
# # summary(cau_c_lm_domc)
# # summary(cau_g_lm_domc)
# # summary(epn_lm_domc)
# # summary(epn_c_lm_domc)
# # summary(epn_g_lm_domc)
# # summary(epz_lm_domc)
# # summary(epz_c_lm_domc)
# # summary(epz_g_lm_domc)
# # summary(wp_lm_domc)
# # summary(wp_c_lm_domc)
# # summary(wp_g_lm_domc)
# # summary(epwp_lm_domc)
# # summary(epwp_c_lm_domc)
# # summary(epwp_g_lm_domc)
# summary(nzm_lm_domc)
# # summary(nzm_c_lm_domc)
# # summary(nzm_g_lm_domc)
# summary(cim_lm_domc)
# # summary(cim_c_lm_domc)
# # summary(cim_g_lm_domc)
# summary(samoan_lm_domc)
# # summary(samoan_c_lm_domc)
# # summary(samoan_g_lm_domc)
# summary(tongan_lm_domc)
# # summary(tongan_c_lm_domc)
# # summary(tongan_g_lm_domc)
# # summary(combined_poly_lm_domc)
# # summary(combined_all_lm_domc)
# confint(cau_lm_domc)
# # confint(cau_c_lm_domc)
# # confint(cau_g_lm_domc)
# # confint(epn_lm_domc)
# # confint(epn_c_lm_domc)
# # confint(epn_g_lm_domc)
# # confint(epz_lm_domc)
# # confint(epz_c_lm_domc)
# # confint(epz_g_lm_domc)
# # confint(wp_lm_domc)
# # confint(wp_c_lm_domc)
# # confint(wp_g_lm_domc)
# # confint(epwp_lm_domc)
# # confint(epwp_c_lm_domc)
# # confint(epwp_g_lm_domc)
# confint(nzm_lm_domc)
# # confint(nzm_c_lm_domc)
# # confint(nzm_g_lm_domc)
# confint(cim_lm_domc)
# # confint(cim_c_lm_domc)
# # confint(cim_g_lm_domc)
# confint(samoan_lm_domc)
# # confint(samoan_c_lm_domc)
# # confint(samoan_g_lm_domc)
# confint(tongan_lm_domc)
# # confint(tongan_c_lm_domc)
# confint(tongan_g_lm_domc)
# confint(combined_poly_lm_domc)
# confint(combined_all_lm_domc)

round(cbind((cbind(beta= coef(cau_lm_domc), confint(cau_lm_domc))),Pvalue= summary(cau_lm_domc)$coefficients[,4]),3)
round(cbind((cbind(beta=coef(nzm_lm_domc), confint(nzm_lm_domc))), Pvalue=summary(nzm_lm_domc)$coefficients[,4]), 3)
round(cbind((cbind(beta=coef(cim_lm_domc), confint(cim_lm_domc))), Pvalue=summary(cim_lm_domc)$coefficients[,4]), 3)
round(cbind((cbind(beta=coef(samoan_lm_domc), confint(samoan_lm_domc))), Pvalue=summary(samoan_lm_domc)$coefficients[,4]),3)
round(cbind((cbind(beta=coef(tongan_lm_domc), confint(tongan_lm_domc))), Pvalue=summary(tongan_lm_domc)$coefficients[,4]),3)
round(cbind((cbind(beta=coef(combined_poly_lm_domc), confint(combined_poly_lm_domc))), Pvalue=summary(combined_poly_lm_domc)$coefficients[,4]),3)
round(cbind((cbind(beta=coef(combined_all_lm_domc), confint(combined_all_lm_domc))), Pvalue=summary(combined_all_lm_domc)$coefficients[,4]),3)

sink()

domc_table=function(x){write.table(x, file="domc_table.csv",sep="\t", quote=FALSE, append=TRUE)}
# domc_table(summary(cau_lm_domc)$coefficients)
# # domc_table(summary(cau_c_lm_domc)$coefficients)
# # domc_table(summary(cau_g_lm_domc)$coefficients)
# # domc_table(summary(epn_lm_domc)$coefficients)
# # domc_table(summary(epn_c_lm_domc)$coefficients)
# # domc_table(summary(epn_g_lm_domc)$coefficients)
# # domc_table(summary(epz_lm_domc)$coefficients)
# # domc_table(summary(epz_c_lm_domc)$coefficients)
# # domc_table(summary(epz_g_lm_domc)$coefficients)
# # domc_table(summary(wp_lm_domc)$coefficients)
# # domc_table(summary(wp_c_lm_domc)$coefficients)
# # domc_table(summary(wp_g_lm_domc)$coefficients)
# # domc_table(summary(epwp_lm_domc)$coefficients)
# # domc_table(summary(epwp_c_lm_domc)$coefficients)
# # domc_table(summary(epwp_g_lm_domc)$coefficients)
# domc_table(summary(nzm_lm_domc)$coefficients)
# # domc_table(summary(nzm_c_lm_domc)$coefficients)
# # domc_table(summary(nzm_g_lm_domc)$coefficients)
# domc_table(summary(cim_lm_domc)$coefficients)
# # domc_table(summary(cim_c_lm_domc)$coefficients)
# # domc_table(summary(cim_g_lm_domc)$coefficients)
# domc_table(summary(samoan_lm_domc)$coefficients)
# # domc_table(summary(samoan_c_lm_domc)$coefficients)
# # domc_table(summary(samoan_g_lm_domc)$coefficients)
# domc_table(summary(tongan_lm_domc)$coefficients)
# # domc_table(summary(tongan_c_lm_domc)$coefficients)
# # domc_table(summary(tongan_g_lm_domc)$coefficients)
# # domc_table(summary(combined_poly_lm_domc)$coefficients)
# # domc_table(summary(combined_all_lm_domc)$coefficients)
# domc_table(confint(cau_lm_domc))
# # domc_table(confint(cau_c_lm_domc))
# # domc_table(confint(cau_g_lm_domc))
# # domc_table(confint(epn_lm_domc))
# # domc_table(confint(epn_c_lm_domc))
# # domc_table(confint(epn_g_lm_domc))
# # domc_table(confint(epz_lm_domc))
# # domc_table(confint(epz_c_lm_domc))
# # domc_table(confint(epz_g_lm_domc))
# # domc_table(confint(wp_lm_domc))
# # domc_table(confint(wp_c_lm_domc))
# # domc_table(confint(wp_g_lm_domc))
# # domc_table(confint(epwp_lm_domc))
# # domc_table(confint(epwp_c_lm_domc))
# # domc_table(confint(epwp_g_lm_domc))
# domc_table(confint(nzm_lm_domc))
# # domc_table(confint(nzm_c_lm_domc))
# # domc_table(confint(nzm_g_lm_domc))
# domc_table(confint(cim_lm_domc))
# # domc_table(confint(cim_c_lm_domc))
# # domc_table(confint(cim_g_lm_domc))
# domc_table(confint(samoan_lm_domc))
# # domc_table(confint(samoan_c_lm_domc))
# # domc_table(confint(samoan_g_lm_domc))
# domc_table(confint(tongan_lm_domc))
# # domc_table(confint(tongan_c_lm_domc))
# # domc_table(confint(tongan_g_lm_domc))
# # domc_table(confint(combined_poly_lm_domc))
# # domc_table(confint(combined_all_lm_domc))
domc_table(round(cbind((cbind(beta= coef(cau_lm_domc), confint(cau_lm_domc))),Pvalue= summary(cau_lm_domc)$coefficients[,4]),3))
domc_table(round(cbind((cbind(beta=coef(nzm_lm_domc), confint(nzm_lm_domc))), Pvalue=summary(nzm_lm_domc)$coefficients[,4]),3))
domc_table(round(cbind((cbind(beta=coef(cim_lm_domc), confint(cim_lm_domc))), Pvalue=summary(cim_lm_domc)$coefficients[,4]),3))
domc_table(round(cbind((cbind(beta=coef(samoan_lm_domc), confint(samoan_lm_domc))), Pvalue=summary(samoan_lm_domc)$coefficients[,4]),3))
domc_table(round(cbind((cbind(beta=coef(tongan_lm_domc), confint(tongan_lm_domc))), Pvalue=summary(tongan_lm_domc)$coefficients[,4]),3))
domc_table(round(cbind((cbind(beta=coef(combined_poly_lm_domc), confint(combined_poly_lm_domc))), Pvalue=summary(combined_poly_lm_domc)$coefficients[,4]),3))
domc_table(round(cbind((cbind(beta=coef(combined_all_lm_domc), confint(combined_all_lm_domc))), Pvalue=summary(combined_all_lm_domc)$coefficients[,4]),3))


#################################################
## regressions DOMINANT TT MODEL ###############
##############################################
cau_lm_domt=lm(CAU$BMI ~ as.factor(CAU$FULLCAUGTAFF) + CAU$AGECOL + as.factor(CAU$SEX.x) + as.factor(CAU$DIABETES)  + as.factor(CAU$DOM_t))
cau_g_lm_domt=lm(CAU_g$BMI ~ CAU_g$AGECOL + as.factor(CAU_g$SEX.x) + as.factor(CAU_g$DIABETES)  + as.factor(CAU_g$DOM_t))
cau_c_lm_domt=lm(CAU_c$BMI ~ CAU_c$AGECOL + as.factor(CAU_c$SEX.x) + as.factor(CAU_c$DIABETES)  + as.factor(CAU_c$DOM_t))

wp_lm_domt=lm(WP$BMI ~ as.factor(WP$FULLWPGTAFF) + WP$AGECOL + as.factor(WP$SEX.x) + as.factor(WP$DIABETES) +WP$STANCESTRY+ as.factor(WP$DOM_t))
wp_g_lm_domt=lm(WP_g$BMI ~ WP_g$AGECOL + as.factor(WP_g$SEX.x) + as.factor(WP_g$DIABETES) +WP_g$STANCESTRY+ as.factor(WP_g$DOM_t))
wp_c_lm_domt=lm(WP_c$BMI ~ WP_c$AGECOL + as.factor(WP_c$SEX.x) + as.factor(WP_c$DIABETES) +WP_c$STANCESTRY+ as.factor(WP_c$DOM_t))

epn_lm_domt=lm(EPN$BMI ~ as.factor(EPN$FULLEPGTAFF) + EPN$AGECOL + as.factor(EPN$SEX.x) + as.factor(EPN$DIABETES) +EPN$STANCESTRY + as.factor(EPN$DOM_t))
epn_g_lm_domt=lm(EPN_g$BMI ~ EPN_g$AGECOL + as.factor(EPN_g$SEX.x) + as.factor(EPN_g$DIABETES) +EPN_g$STANCESTRY +as.factor(EPN_g$DOM_t))
epn_c_lm_domt=lm(EPN_c$BMI ~ EPN_c$AGECOL + as.factor(EPN_c$SEX.x) + as.factor(EPN_c$DIABETES) +EPN_c$STANCESTRY + as.factor(EPN_c$DOM_t))

epz_lm_domt=lm(EPZ$BMI ~ as.factor(EPZ$FULLEPGTAFF) + EPZ$AGECOL + as.factor(EPZ$SEX.x) + as.factor(EPZ$DIABETES) +EPZ$STANCESTRY + as.factor(EPZ$DOM_t))
epz_g_lm_domt=lm(EPZ_g$BMI ~ EPZ_g$AGECOL + as.factor(EPZ_g$SEX.x) + as.factor(EPZ_g$DIABETES) +EPZ_g$STANCESTRY + as.factor(EPZ_g$DOM_t))
epz_c_lm_domt=lm(EPZ_c$BMI ~ EPZ_c$AGECOL + as.factor(EPZ_c$SEX.x) + as.factor(EPZ_c$DIABETES) +EPZ_c$STANCESTRY + as.factor(EPZ_c$DOM_t))

epwp_lm_domt=lm(EPWP$BMI ~ as.factor(EPWP$FULLEPWPGTAFF) + EPWP$AGECOL + as.factor(EPWP$SEX.x) + as.factor(EPWP$DIABETES) +EPWP$STANCESTRY + as.factor(EPWP$DOM_t))
epwp_g_lm_domt=lm(EPWP_g$BMI ~ EPWP_g$AGECOL + as.factor(EPWP_g$SEX.x) + as.factor(EPWP_g$DIABETES) +EPWP_g$STANCESTRY + as.factor(EPWP_g$DOM_t))
epwp_c_lm_domt=lm(EPWP_c$BMI ~ EPWP_c$AGECOL + as.factor(EPWP_c$SEX.x) + as.factor(EPWP_c$DIABETES) +EPWP_c$STANCESTRY + as.factor(EPWP_c$DOM_t))

nzm_lm_domt=lm(nzm$BMI ~ as.factor(nzm$FULLEPGTAFF) + nzm$AGECOL + as.factor(nzm$SEX.x) + as.factor(nzm$DIABETES) +nzm$STANCESTRY+ as.factor(nzm$DOM_t))
nzm_g_lm_domt=lm(nzm_g$BMI ~ nzm_g$AGECOL + as.factor(nzm_g$SEX.x) + as.factor(nzm_g$DIABETES) +nzm_g$STANCESTRY+ as.factor(nzm_g$DOM_t))
nzm_c_lm_domt=lm(nzm_c$BMI ~ nzm_c$AGECOL + as.factor(nzm_c$SEX.x) + as.factor(nzm_c$DIABETES) +nzm_c$STANCESTRY+ as.factor(nzm_c$DOM_t))

cim_lm_domt=lm(cim$BMI ~ as.factor(cim$FULLEPGTAFF) + cim$AGECOL + as.factor(cim$SEX.x) + as.factor(cim$DIABETES) +cim$STANCESTRY+ as.factor(cim$DOM_t))
cim_g_lm_domt=lm(cim_g$BMI ~ cim_g$AGECOL + as.factor(cim_g$SEX.x) + as.factor(cim_g$DIABETES) +cim_g$STANCESTRY+ as.factor(cim_g$DOM_t))
cim_c_lm_domt=lm(cim_c$BMI ~ cim_c$AGECOL + as.factor(cim_c$SEX.x) + as.factor(cim_c$DIABETES) +cim_c$STANCESTRY+ as.factor(cim_c$DOM_t))

samoan_lm_domt=lm(samoan$BMI ~ as.factor(samoan$FULLWPGTAFF) + samoan$AGECOL + as.factor(samoan$SEX.x) + as.factor(samoan$DIABETES) +samoan$STANCESTRY+ as.factor(samoan$DOM_t))
samoan_g_lm_domt=lm(samoan_g$BMI ~ samoan_g$AGECOL + as.factor(samoan_g$SEX.x) + as.factor(samoan_g$DIABETES) +samoan_g$STANCESTRY+ as.factor(samoan_g$DOM_t))
samoan_c_lm_domt=lm(samoan_c$BMI ~ samoan_c$AGECOL + as.factor(samoan_c$SEX.x) + as.factor(samoan_c$DIABETES) +samoan_c$STANCESTRY+ as.factor(samoan_c$DOM_t))

tongan_lm_domt=lm(tongan$BMI ~ as.factor(tongan$FULLWPGTAFF) + tongan$AGECOL + as.factor(tongan$SEX.x) + as.factor(tongan$DIABETES) +tongan$STANCESTRY+ as.factor(tongan$DOM_t))
tongan_g_lm_domt=lm(tongan_g$BMI ~ tongan_g$AGECOL + as.factor(tongan_g$SEX.x) + as.factor(tongan_g$DIABETES) +tongan_g$STANCESTRY+ as.factor(tongan_g$DOM_t))
tongan_c_lm_domt=lm(tongan_c$BMI ~ tongan_c$AGECOL + as.factor(tongan_c$SEX.x) + as.factor(tongan_c$DIABETES) +tongan_c$STANCESTRY+ as.factor(tongan_c$DOM_t))

sink(file="dominant_TT_model.txt")
# summary(cau_lm_domt)
# # summary(cau_c_lm_domt)
# # summary(cau_g_lm_domt)
# # summary(epn_lm_domt)
# # summary(epn_c_lm_domt)
# # summary(epn_g_lm_domt)
# # summary(epz_lm_domt)
# # summary(epz_c_lm_domt)
# # summary(epz_g_lm_domt)
# # summary(wp_lm_domt)
# # summary(wp_c_lm_domt)
# # summary(wp_g_lm_domt)
# # summary(epwp_lm_domt)
# # summary(epwp_c_lm_domt)
# # summary(epwp_g_lm_domt)
# summary(nzm_lm_domt)
# # summary(nzm_c_lm_domt)
# # summary(nzm_g_lm_domt)
# summary(cim_lm_domt)
# # summary(cim_c_lm_domt)
# # summary(cim_g_lm_domt)
# summary(samoan_lm_domt)
# # summary(samoan_c_lm_domt)
# # summary(samoan_g_lm_domt)
# summary(tongan_lm_domt)
# # summary(tongan_c_lm_domt)
# # summary(tongan_g_lm_domt)
# # summary(combined_poly_lm_domt)
# # summary(combined_all_lm_domt)
# confint(cau_lm_domt)
# # confint(cau_c_lm_domt)
# # confint(cau_g_lm_domt)
# # confint(epn_lm_domt)
# # confint(epn_c_lm_domt)
# # confint(epn_g_lm_domt)
# # confint(epz_lm_domt)
# # confint(epz_c_lm_domt)
# # confint(epz_g_lm_domt)
# # confint(wp_lm_domt)
# # confint(wp_c_lm_domt)
# # confint(wp_g_lm_domt)
# # confint(epwp_lm_domt)
# # confint(epwp_c_lm_domt)
# # confint(epwp_g_lm_domt)
# confint(nzm_lm_domt)
# # confint(nzm_c_lm_domt)
# # confint(nzm_g_lm_domt)
# confint(cim_lm_domt)
# # confint(cim_c_lm_domt)
# # confint(cim_g_lm_domt)
# confint(samoan_lm_domt)
# # confint(samoan_c_lm_domt)
# # confint(samoan_g_lm_domt)
# confint(tongan_lm_domt)
# # confint(tongan_c_lm_domt)
# # confint(tongan_g_lm_domt)
# # confint(combined_poly_lm_domt)
# # confint(combined_all_lm_domt)
round(cbind((cbind(beta= coef(cau_lm_domt), confint(cau_lm_domt))),Pvalue= summary(cau_lm_domt)$coefficients[,4]),3)
round(cbind((cbind(beta=coef(nzm_lm_domt), confint(nzm_lm_domt))), Pvalue=summary(nzm_lm_domt)$coefficients[,4]), 3)
round(cbind((cbind(beta=coef(cim_lm_domt), confint(cim_lm_domt))), Pvalue=summary(cim_lm_domt)$coefficients[,4]), 3)
round(cbind((cbind(beta=coef(samoan_lm_domt), confint(samoan_lm_domt))), Pvalue=summary(samoan_lm_domt)$coefficients[,4]),3)
round(cbind((cbind(beta=coef(tongan_lm_domt), confint(tongan_lm_domt))), Pvalue=summary(tongan_lm_domt)$coefficients[,4]),3)
round(cbind((cbind(beta=coef(combined_poly_lm_domt), confint(combined_poly_lm_domt))), Pvalue=summary(combined_poly_lm_domt)$coefficients[,4]),3)
round(cbind((cbind(beta=coef(combined_all_lm_domt), confint(combined_all_lm_domt))), Pvalue=summary(combined_all_lm_domt)$coefficients[,4]),3)
sink()

domt_table=function(x){write.table(x, file="domt_table.csv",sep="\t", quote=FALSE, append=TRUE)}
# domt_table(summary(cau_lm_domt)$coefficients)
# #domt_table(summary(cau_c_lm_domt)$coefficients)
# #domt_table(summary(cau_g_lm_domt)$coefficients)
# #domt_table(summary(epn_lm_domt)$coefficients)
# #domt_table(summary(epn_c_lm_domt)$coefficients)
# #domt_table(summary(epn_g_lm_domt)$coefficients)
# #domt_table(summary(epz_lm_domt)$coefficients)
# #domt_table(summary(epz_c_lm_domt)$coefficients)
# #domt_table(summary(epz_g_lm_domt)$coefficients)
# #domt_table(summary(wp_lm_domt)$coefficients)
# #domt_table(summary(wp_c_lm_domt)$coefficients)
# #domt_table(summary(wp_g_lm_domt)$coefficients)
# #domt_table(summary(epwp_lm_domt)$coefficients)
# #domt_table(summary(epwp_c_lm_domt)$coefficients)
# #domt_table(summary(epwp_g_lm_domt)$coefficients)
# domt_table(summary(nzm_lm_domt)$coefficients)
# #domt_table(summary(nzm_c_lm_domt)$coefficients)
# #domt_table(summary(nzm_g_lm_domt)$coefficients)
# domt_table(summary(cim_lm_domt)$coefficients)
# #domt_table(summary(cim_c_lm_domt)$coefficients)
# #domt_table(summary(cim_g_lm_domt)$coefficients)
# domt_table(summary(samoan_lm_domt)$coefficients)
# #domt_table(summary(samoan_c_lm_domt)$coefficients)
# #domt_table(summary(samoan_g_lm_domt)$coefficients)
# domt_table(summary(tongan_lm_domt)$coefficients)
# #domt_table(summary(tongan_c_lm_domt)$coefficients)
# #domt_table(summary(tongan_g_lm_domt)$coefficients)
# # domt_table(summary(combined_poly_lm_domt)$coefficients)
# # domt_table(summary(combined_all_lm_domt)$coefficients)
# domt_table(confint(cau_lm_domt))
# # domt_table(confint(cau_c_lm_domt))
# # domt_table(confint(cau_g_lm_domt))
# # domt_table(confint(epn_lm_domt))
# # domt_table(confint(epn_c_lm_domt))
# # domt_table(confint(epn_g_lm_domt))
# # domt_table(confint(epz_lm_domt))
# # domt_table(confint(epz_c_lm_domt))
# # domt_table(confint(epz_g_lm_domt))
# # domt_table(confint(wp_lm_domt))
# # domt_table(confint(wp_c_lm_domt))
# # domt_table(confint(wp_g_lm_domt))
# # domt_table(confint(epwp_lm_domt))
# # domt_table(confint(epwp_c_lm_domt))
# # domt_table(confint(epwp_g_lm_domt))
# domt_table(confint(nzm_lm_domt))
# # domt_table(confint(nzm_c_lm_domt))
# # domt_table(confint(nzm_g_lm_domt))
# domt_table(confint(cim_lm_domt))
# # domt_table(confint(cim_c_lm_domt))
# # domt_table(confint(cim_g_lm_domt))
# domt_table(confint(samoan_lm_domt))
# # domt_table(confint(samoan_c_lm_domt))
# # domt_table(confint(samoan_g_lm_domt))
# domt_table(confint(tongan_lm_domt))
# # domt_table(confint(tongan_c_lm_domt))
# # domt_table(confint(tongan_g_lm_domt))
# # domt_table(confint(combined_poly_lm_domt))
# # domt_table(confint(combined_all_lm_domt))
domt_table(round(cbind((cbind(beta= coef(cau_lm_domt), confint(cau_lm_domt))),Pvalue= summary(cau_lm_domt)$coefficients[,4]),3))
domt_table(round(cbind((cbind(beta=coef(nzm_lm_domt), confint(nzm_lm_domt))), Pvalue=summary(nzm_lm_domt)$coefficients[,4]),3))
domt_table(round(cbind((cbind(beta=coef(cim_lm_domt), confint(cim_lm_domt))), Pvalue=summary(cim_lm_domt)$coefficients[,4]),3))
domt_table(round(cbind((cbind(beta=coef(samoan_lm_domt), confint(samoan_lm_domt))), Pvalue=summary(samoan_lm_domt)$coefficients[,4]),3))
domt_table(round(cbind((cbind(beta=coef(tongan_lm_domt), confint(tongan_lm_domt))), Pvalue=summary(tongan_lm_domt)$coefficients[,4]),3))
domt_table(round(cbind((cbind(beta=coef(combined_poly_lm_domt), confint(combined_poly_lm_domt))), Pvalue=summary(combined_poly_lm_domt)$coefficients[,4]),3))
domt_table(round(cbind((cbind(beta=coef(combined_all_lm_domt), confint(combined_all_lm_domt))), Pvalue=summary(combined_all_lm_domt)$coefficients[,4]),3))


#################################################
## regressions HET ADVANTAGE MODEL ###############
##############################################
cau_lm_het_adv=lm(CAU$BMI ~ as.factor(CAU$FULLCAUGTAFF) + CAU$AGECOL + as.factor(CAU$SEX.x) + as.factor(CAU$DIABETES)  + as.factor(CAU$het_adv))
cau_g_lm_het_adv=lm(CAU_g$BMI ~ CAU_g$AGECOL + as.factor(CAU_g$SEX.x) + as.factor(CAU_g$DIABETES)  + as.factor(CAU_g$het_adv))
cau_c_lm_het_adv=lm(CAU_c$BMI ~ CAU_c$AGECOL + as.factor(CAU_c$SEX.x) + as.factor(CAU_c$DIABETES)  + as.factor(CAU_c$het_adv))

wp_lm_het_adv=lm(WP$BMI ~ as.factor(WP$FULLWPGTAFF) + WP$AGECOL + as.factor(WP$SEX.x) + as.factor(WP$DIABETES) +WP$STANCESTRY+ as.factor(WP$het_adv))
wp_g_lm_het_adv=lm(WP_g$BMI ~ WP_g$AGECOL + as.factor(WP_g$SEX.x) + as.factor(WP_g$DIABETES) +WP_g$STANCESTRY+ as.factor(WP_g$het_adv))
wp_c_lm_het_adv=lm(WP_c$BMI ~ WP_c$AGECOL + as.factor(WP_c$SEX.x) + as.factor(WP_c$DIABETES) +WP_c$STANCESTRY+ as.factor(WP_c$het_adv))

epn_lm_het_adv=lm(EPN$BMI ~ as.factor(EPN$FULLEPGTAFF) + EPN$AGECOL + as.factor(EPN$SEX.x) + as.factor(EPN$DIABETES) +EPN$STANCESTRY + as.factor(EPN$het_adv))
epn_g_lm_het_adv=lm(EPN_g$BMI ~ EPN_g$AGECOL + as.factor(EPN_g$SEX.x) + as.factor(EPN_g$DIABETES) +EPN_g$STANCESTRY +as.factor(EPN_g$het_adv))
epn_c_lm_het_adv=lm(EPN_c$BMI ~ EPN_c$AGECOL + as.factor(EPN_c$SEX.x) + as.factor(EPN_c$DIABETES) +EPN_c$STANCESTRY + as.factor(EPN_c$het_adv))

epz_lm_het_adv=lm(EPZ$BMI ~ as.factor(EPZ$FULLEPGTAFF) + EPZ$AGECOL + as.factor(EPZ$SEX.x) + as.factor(EPZ$DIABETES) +EPZ$STANCESTRY + as.factor(EPZ$het_adv))
epz_g_lm_het_adv=lm(EPZ_g$BMI ~ EPZ_g$AGECOL + as.factor(EPZ_g$SEX.x) + as.factor(EPZ_g$DIABETES) +EPZ_g$STANCESTRY + as.factor(EPZ_g$het_adv))
epz_c_lm_het_adv=lm(EPZ_c$BMI ~ EPZ_c$AGECOL + as.factor(EPZ_c$SEX.x) + as.factor(EPZ_c$DIABETES) +EPZ_c$STANCESTRY + as.factor(EPZ_c$het_adv))

epwp_lm_het_adv=lm(EPWP$BMI ~ as.factor(EPWP$FULLEPWPGTAFF) + EPWP$AGECOL + as.factor(EPWP$SEX.x) + as.factor(EPWP$DIABETES) +EPWP$STANCESTRY + as.factor(EPWP$het_adv))
epwp_g_lm_het_adv=lm(EPWP_g$BMI ~ EPWP_g$AGECOL + as.factor(EPWP_g$SEX.x) + as.factor(EPWP_g$DIABETES) +EPWP_g$STANCESTRY + as.factor(EPWP_g$het_adv))
epwp_c_lm_het_adv=lm(EPWP_c$BMI ~ EPWP_c$AGECOL + as.factor(EPWP_c$SEX.x) + as.factor(EPWP_c$DIABETES) +EPWP_c$STANCESTRY + as.factor(EPWP_c$het_adv))

nzm_lm_het_adv=lm(nzm$BMI ~ as.factor(nzm$FULLEPGTAFF) + nzm$AGECOL + as.factor(nzm$SEX.x) + as.factor(nzm$DIABETES) +nzm$STANCESTRY+ as.factor(nzm$het_adv))
nzm_g_lm_het_adv=lm(nzm_g$BMI ~ nzm_g$AGECOL + as.factor(nzm_g$SEX.x) + as.factor(nzm_g$DIABETES) +nzm_g$STANCESTRY+ as.factor(nzm_g$het_adv))
nzm_c_lm_het_adv=lm(nzm_c$BMI ~ nzm_c$AGECOL + as.factor(nzm_c$SEX.x) + as.factor(nzm_c$DIABETES) +nzm_c$STANCESTRY+ as.factor(nzm_c$het_adv))

cim_lm_het_adv=lm(cim$BMI ~ as.factor(cim$FULLEPGTAFF) + cim$AGECOL + as.factor(cim$SEX.x) + as.factor(cim$DIABETES) +cim$STANCESTRY+ as.factor(cim$het_adv))
cim_g_lm_het_adv=lm(cim_g$BMI ~ cim_g$AGECOL + as.factor(cim_g$SEX.x) + as.factor(cim_g$DIABETES) +cim_g$STANCESTRY+ as.factor(cim_g$het_adv))
cim_c_lm_het_adv=lm(cim_c$BMI ~ cim_c$AGECOL + as.factor(cim_c$SEX.x) + as.factor(cim_c$DIABETES) +cim_c$STANCESTRY+ as.factor(cim_c$het_adv))

samoan_lm_het_adv=lm(samoan$BMI ~ as.factor(samoan$FULLWPGTAFF) + samoan$AGECOL + as.factor(samoan$SEX.x) + as.factor(samoan$DIABETES) +samoan$STANCESTRY+ as.factor(samoan$het_adv))
samoan_g_lm_het_adv=lm(samoan_g$BMI ~ samoan_g$AGECOL + as.factor(samoan_g$SEX.x) + as.factor(samoan_g$DIABETES) +samoan_g$STANCESTRY+ as.factor(samoan_g$het_adv))
samoan_c_lm_het_adv=lm(samoan_c$BMI ~ samoan_c$AGECOL + as.factor(samoan_c$SEX.x) + as.factor(samoan_c$DIABETES) +samoan_c$STANCESTRY+ as.factor(samoan_c$het_adv))

tongan_lm_het_adv=lm(tongan$BMI ~ as.factor(tongan$FULLWPGTAFF) + tongan$AGECOL + as.factor(tongan$SEX.x) + as.factor(tongan$DIABETES) +tongan$STANCESTRY+ as.factor(tongan$het_adv))
tongan_g_lm_het_adv=lm(tongan_g$BMI ~ tongan_g$AGECOL + as.factor(tongan_g$SEX.x) + as.factor(tongan_g$DIABETES) +tongan_g$STANCESTRY+ as.factor(tongan_g$het_adv))
tongan_c_lm_het_adv=lm(tongan_c$BMI ~ tongan_c$AGECOL + as.factor(tongan_c$SEX.x) + as.factor(tongan_c$DIABETES) +tongan_c$STANCESTRY+ as.factor(tongan_c$het_adv))

sink(file="het_advantage_model.txt")
# summary(cau_lm_het_adv)
# # summary(cau_c_lm_het_adv)
# # summary(cau_g_lm_het_adv)
# # summary(epn_lm_het_adv)
# # summary(epn_c_lm_het_adv)
# # summary(epn_g_lm_het_adv)
# # summary(epz_lm_het_adv)
# # summary(epz_c_lm_het_adv)
# # summary(epz_g_lm_het_adv)
# # summary(wp_lm_het_adv)
# # summary(wp_c_lm_het_adv)
# # summary(wp_g_lm_het_adv)
# # summary(epwp_lm_het_adv)
# # summary(epwp_c_lm_het_adv)
# # summary(epwp_g_lm_het_adv)
# summary(nzm_lm_het_adv)
# # summary(nzm_c_lm_het_adv)
# # summary(nzm_g_lm_het_adv)
# summary(cim_lm_het_adv)
# # summary(cim_c_lm_het_adv)
# # summary(cim_g_lm_het_adv)
# summary(samoan_lm_het_adv)
# # summary(samoan_c_lm_het_adv)
# # summary(samoan_g_lm_het_adv)
# summary(tongan_lm_het_adv)
# # summary(tongan_c_lm_het_adv)
# # summary(tongan_g_lm_het_adv)
# # summary(combined_poly_lm_het_adv)
# # summary(combined_all_lm_het_adv)
# confint(cau_lm_het_adv)
# # confint(cau_c_lm_het_adv)
# # confint(cau_g_lm_het_adv)
# # confint(epn_lm_het_adv)
# # confint(epn_c_lm_het_adv)
# # confint(epn_g_lm_het_adv)
# # confint(epz_lm_het_adv)
# # confint(epz_c_lm_het_adv)
# # confint(epz_g_lm_het_adv)
# # confint(wp_lm_het_adv)
# # confint(wp_c_lm_het_adv)
# # confint(wp_g_lm_het_adv)
# # confint(epwp_lm_het_adv)
# # confint(epwp_c_lm_het_adv)
# # confint(epwp_g_lm_het_adv)
# confint(nzm_lm_het_adv)
# # confint(nzm_c_lm_het_adv)
# # confint(nzm_g_lm_het_adv)
# confint(cim_lm_het_adv)
# # confint(cim_c_lm_het_adv)
# # confint(cim_g_lm_het_adv)
# confint(samoan_lm_het_adv)
# # confint(samoan_c_lm_het_adv)
# # confint(samoan_g_lm_het_adv)
# confint(tongan_lm_het_adv)
# # confint(tongan_c_lm_het_adv)
# # confint(tongan_g_lm_het_adv)
# # confint(combined_poly_lm_het_adv)
# # confint(combined_all_lm_het_adv)
round(cbind((cbind(beta= coef(cau_lm_het_adv), confint(cau_lm_het_adv))),Pvalue= summary(cau_lm_het_adv)$coefficients[,4]),3)
round(cbind((cbind(beta=coef(nzm_lm_het_adv), confint(nzm_lm_het_adv))), Pvalue=summary(nzm_lm_het_adv)$coefficients[,4]), 3)
round(cbind((cbind(beta=coef(cim_lm_het_adv), confint(cim_lm_het_adv))), Pvalue=summary(cim_lm_het_adv)$coefficients[,4]), 3)
round(cbind((cbind(beta=coef(samoan_lm_het_adv), confint(samoan_lm_het_adv))), Pvalue=summary(samoan_lm_het_adv)$coefficients[,4]),3)
round(cbind((cbind(beta=coef(tongan_lm_het_adv), confint(tongan_lm_het_adv))), Pvalue=summary(tongan_lm_het_adv)$coefficients[,4]),3)
round(cbind((cbind(beta=coef(combined_poly_lm_het_adv), confint(combined_poly_lm_het_adv))), Pvalue=summary(combined_poly_lm_het_adv)$coefficients[,4]),3)
round(cbind((cbind(beta=coef(combined_all_lm_het_adv), confint(combined_all_lm_het_adv))), Pvalue=summary(combined_all_lm_het_adv)$coefficients[,4]),3)
sink()

het_adv_table=function(x){write.table(x, file="het_adv_table.csv",sep="\t", quote=FALSE, append=TRUE)}
# het_adv_table(summary(cau_lm_het_adv)$coefficients)
# # het_adv_table(summary(cau_c_lm_het_adv)$coefficients)
# # het_adv_table(summary(cau_g_lm_het_adv)$coefficients)
# # het_adv_table(summary(epn_lm_het_adv)$coefficients)
# # het_adv_table(summary(epn_c_lm_het_adv)$coefficients)
# # het_adv_table(summary(epn_g_lm_het_adv)$coefficients)
# # het_adv_table(summary(epz_lm_het_adv)$coefficients)
# # het_adv_table(summary(epz_c_lm_het_adv)$coefficients)
# # het_adv_table(summary(epz_g_lm_het_adv)$coefficients)
# # het_adv_table(summary(wp_lm_het_adv)$coefficients)
# # het_adv_table(summary(wp_c_lm_het_adv)$coefficients)
# # het_adv_table(summary(wp_g_lm_het_adv)$coefficients)
# # het_adv_table(summary(epwp_lm_het_adv)$coefficients)
# # het_adv_table(summary(epwp_c_lm_het_adv)$coefficients)
# # het_adv_table(summary(epwp_g_lm_het_adv)$coefficients)
# het_adv_table(summary(nzm_lm_het_adv)$coefficients)
# # het_adv_table(summary(nzm_c_lm_het_adv)$coefficients)
# # het_adv_table(summary(nzm_g_lm_het_adv)$coefficients)
# het_adv_table(summary(cim_lm_het_adv)$coefficients)
# # het_adv_table(summary(cim_c_lm_het_adv$coefficients))
# # het_adv_table(summary(cim_g_lm_het_adv)$coefficients)
# het_adv_table(summary(samoan_lm_het_adv)$coefficients)
# # het_adv_table(summary(samoan_c_lm_het_adv)$coefficients)
# # het_adv_table(summary(samoan_g_lm_het_adv)$coefficients)
# het_adv_table(summary(tongan_lm_het_adv)$coefficients)
# # het_adv_table(summary(tongan_c_lm_het_adv)$coefficients)
# # het_adv_table(summary(tongan_g_lm_het_adv)$coefficients)
# # het_adv_table(summary(combined_poly_lm_het_adv)$coefficients)
# # het_adv_table(summary(combined_all_lm_het_adv)$coefficients)
# het_adv_table(confint(cau_lm_het_adv))
# # het_adv_table(confint(cau_c_lm_het_adv))
# # het_adv_table(confint(cau_g_lm_het_adv))
# # het_adv_table(confint(epn_lm_het_adv))
# # het_adv_table(confint(epn_c_lm_het_adv))
# # het_adv_table(confint(epn_g_lm_het_adv))
# # het_adv_table(confint(epz_lm_het_adv))
# # het_adv_table(confint(epz_c_lm_het_adv))
# # het_adv_table(confint(epz_g_lm_het_adv))
# # het_adv_table(confint(wp_lm_het_adv))
# # het_adv_table(confint(wp_c_lm_het_adv))
# # het_adv_table(confint(wp_g_lm_het_adv))
# # het_adv_table(confint(epwp_lm_het_adv))
# # het_adv_table(confint(epwp_c_lm_het_adv))
# # het_adv_table(confint(epwp_g_lm_het_adv))
# het_adv_table(confint(nzm_lm_het_adv))
# # het_adv_table(confint(nzm_c_lm_het_adv))
# # het_adv_table(confint(nzm_g_lm_het_adv))
# het_adv_table(confint(cim_lm_het_adv))
# # het_adv_table(confint(cim_c_lm_het_adv))
# # het_adv_table(confint(cim_g_lm_het_adv))
# het_adv_table(confint(samoan_lm_het_adv))
# # het_adv_table(confint(samoan_c_lm_het_adv))
# # het_adv_table(confint(samoan_g_lm_het_adv))
# het_adv_table(confint(tongan_lm_het_adv))
# # het_adv_table(confint(tongan_c_lm_het_adv))
# # het_adv_table(confint(tongan_g_lm_het_adv))
# # het_adv_table(confint(combined_poly_lm_het_adv))
# # het_adv_table(confint(combined_all_lm_het_adv))
het_adv_table(round(cbind((cbind(beta= coef(cau_lm_het_adv), confint(cau_lm_het_adv))),Pvalue= summary(cau_lm_het_adv)$coefficients[,4]),3))
het_adv_table(round(cbind((cbind(beta=coef(nzm_lm_het_adv), confint(nzm_lm_het_adv))), Pvalue=summary(nzm_lm_het_adv)$coefficients[,4]),3))
het_adv_table(round(cbind((cbind(beta=coef(cim_lm_het_adv), confint(cim_lm_het_adv))), Pvalue=summary(cim_lm_het_adv)$coefficients[,4]),3))
het_adv_table(round(cbind((cbind(beta=coef(samoan_lm_het_adv), confint(samoan_lm_het_adv))), Pvalue=summary(samoan_lm_het_adv)$coefficients[,4]),3))
het_adv_table(round(cbind((cbind(beta=coef(tongan_lm_het_adv), confint(tongan_lm_het_adv))), Pvalue=summary(tongan_lm_het_adv)$coefficients[,4]),3))
het_adv_table(round(cbind((cbind(beta=coef(combined_poly_lm_het_adv), confint(combined_poly_lm_het_adv))), Pvalue=summary(combined_poly_lm_het_adv)$coefficients[,4]),3))
het_adv_table(round(cbind((cbind(beta=coef(combined_all_lm_het_adv), confint(combined_all_lm_het_adv))), Pvalue=summary(combined_all_lm_het_adv)$coefficients[,4]),3))


basic_info=function(x){
  print("BMI")
  print(summary(x$BMI))
  print("AGECOL")
  print(summary(x$AGECOL))
  print("SEX")
  print(table(x$SEX.x,exclude=NULL))
  print("DIABETES")
  print(table(x$DIABETES,exclude=NULL))
  print("STANCESTRY")
  print(summary(x$STANCESTRY))
  print("RS8192678_CC1_CT2_TT3")
  print(table(x$RS8192678_CC1_CT2_TT3,exclude=NULL))
  maf=round((table(x$RS8192678_CC1_CT2_TT3,exclude=NULL)[2] + 2 * table(x$RS8192678_CC1_CT2_TT3,exclude=NULL)[3])/(2 * sum(table(x$RS8192678_CC1_CT2_TT3,exclude=NULL))),digits = 3)
  print("MAF")
  print(maf)
  print("FULLCAUGTAFF")
  print(table(x$FULLCAUGTAFF, exclude=NULL))
  print("FULLEPGTAFF")
  print(table(x$FULLEPGTAFF, exclude=NULL))
  print("FULLWPGTAFF")
  print(table(x$FULLWPGTAFF, exclude=NULL))
  print("FULLEPWPGTAFF")
  print(table(x$FULLEPWPGTAFF, exclude=NULL))
}
